// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 73KhD343S1ps4YNpRNR2Mg
// Component: 8lhdPwd74f
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_paper_house.module.css"; // plasmic-import: 73KhD343S1ps4YNpRNR2Mg/projectcss
import sty from "./PlasmicFaq.module.css"; // plasmic-import: 8lhdPwd74f/css
import IconsArrowDownSimpleLineIcon from "./icons/PlasmicIcon__IconsArrowDownSimpleLine"; // plasmic-import: pCMzSkne9Gk/icon
import IconsHomeFilledIcon from "./icons/PlasmicIcon__IconsHomeFilled"; // plasmic-import: fTYKAUyHxzV/icon
import IconsCircleAndSquareFilledIcon from "./icons/PlasmicIcon__IconsCircleAndSquareFilled"; // plasmic-import: qY0LseDkOzz/icon
import IconsLightningFilledIcon from "./icons/PlasmicIcon__IconsLightningFilled"; // plasmic-import: 45naGZu_SdP/icon
import IconsPenFilledIcon from "./icons/PlasmicIcon__IconsPenFilled"; // plasmic-import: 1khrMQdANwK/icon
import IconsArrowLeft2Line3Icon from "./icons/PlasmicIcon__IconsArrowLeft2Line3"; // plasmic-import: _EYFakmeLa1/icon
import IconsArrowRight2Line2Icon from "./icons/PlasmicIcon__IconsArrowRight2Line2"; // plasmic-import: ojVcl76mJo1/icon

export const PlasmicFaq__VariantProps = new Array();

export const PlasmicFaq__ArgProps = new Array();

function PlasmicFaq__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"faqDesktopLight"}
            data-plasmic-override={overrides.faqDesktopLight}
            className={classNames(projectcss.all, sty.faqDesktopLight)}
          >
            <div
              data-plasmic-name={"navDefaultDesktopLight"}
              data-plasmic-override={overrides.navDefaultDesktopLight}
              className={classNames(projectcss.all, sty.navDefaultDesktopLight)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"navContent"}
                data-plasmic-override={overrides.navContent}
                hasGap={true}
                className={classNames(projectcss.all, sty.navContent)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"leftContent"}
                  data-plasmic-override={overrides.leftContent}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.leftContent)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"logo"}
                    data-plasmic-override={overrides.logo}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.logo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hoYGn
                      )}
                    >
                      {"Paperhouse"}
                    </div>
                  </p.Stack>

                  <div
                    data-plasmic-name={"divider"}
                    data-plasmic-override={overrides.divider}
                    className={classNames(projectcss.all, sty.divider)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t1Hbo
                    )}
                  >
                    {"Search"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zNQiI
                    )}
                  >
                    {"How it works"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"actions"}
                  data-plasmic-override={overrides.actions}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.actions)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttons"}
                    data-plasmic-override={overrides.buttons}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttons)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button)}
                    >
                      <div
                        data-plasmic-name={"label"}
                        data-plasmic-override={overrides.label}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label
                        )}
                      >
                        {"Create"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button2)}
                    >
                      <div
                        data-plasmic-name={"label2"}
                        data-plasmic-override={overrides.label2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label2
                        )}
                      >
                        {"Open collection"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"faq02DesktopLight"}
              data-plasmic-override={overrides.faq02DesktopLight}
              hasGap={true}
              className={classNames(projectcss.all, sty.faq02DesktopLight)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame20"}
                data-plasmic-override={overrides.frame20}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame20)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame5"}
                  data-plasmic-override={overrides.frame5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame5)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__p9X1J
                      )}
                    >
                      {"learn how to get started"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ekUc0
                      )}
                    >
                      {"Frequently asked questions"}
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fNnYw
                    )}
                  >
                    {
                      "Join Stacks community now to get free updates and also alot of freebies are waiting for you or Contact Support"
                    }
                  </div>
                </p.Stack>

                <div
                  data-plasmic-name={"frame19"}
                  data-plasmic-override={overrides.frame19}
                  className={classNames(projectcss.all, sty.frame19)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame22"}
                    data-plasmic-override={overrides.frame22}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame22)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame11"}
                      data-plasmic-override={overrides.frame11}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame11)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"toggle"}
                        data-plasmic-override={overrides.toggle}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.toggle)}
                      >
                        <div
                          data-plasmic-name={"divider2"}
                          data-plasmic-override={overrides.divider2}
                          className={classNames(projectcss.all, sty.divider2)}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"titleIcon"}
                          data-plasmic-override={overrides.titleIcon}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.titleIcon)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dNZvT
                            )}
                          >
                            {"How does it work"}
                          </div>

                          <IconsArrowDownSimpleLineIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__oQwZe
                            )}
                            role={"img"}
                          />
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame21"}
                      data-plasmic-override={overrides.frame21}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame21)}
                    >
                      <div
                        data-plasmic-name={
                          "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode"
                        }
                        data-plasmic-override={
                          overrides.theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode
                        )}
                      >
                        {
                          'The Stacks series of products: Stacks: Landing Page Kit, Stacks: Portfolio Kit,  Stacks: eCommerce Kit. "Stacks is a production-ready library of stackable content blocks built in React Native. Mix-and-match dozens of responsive elements to quickly configure your favorite landing page layouts or hit the ground running with 10 pre-built templates, all in light or dark mode." '
                        }
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"buttons2"}
                        data-plasmic-override={overrides.buttons2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.buttons2)}
                      >
                        <div
                          data-plasmic-name={"contactUs"}
                          data-plasmic-override={overrides.contactUs}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.contactUs
                          )}
                        >
                          {"Learn more"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame12"}
                      data-plasmic-override={overrides.frame12}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame12)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"toggle2"}
                        data-plasmic-override={overrides.toggle2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.toggle2)}
                      >
                        <div
                          data-plasmic-name={"divider3"}
                          data-plasmic-override={overrides.divider3}
                          className={classNames(projectcss.all, sty.divider3)}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"titleIcon2"}
                          data-plasmic-override={overrides.titleIcon2}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.titleIcon2)}
                        >
                          <div
                            data-plasmic-name={"howDoesItWork"}
                            data-plasmic-override={overrides.howDoesItWork}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.howDoesItWork
                            )}
                          >
                            {"How to start with Stacks"}
                          </div>

                          <IconsArrowDownSimpleLineIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9QyM5
                            )}
                            role={"img"}
                          />
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"toggle3"}
                        data-plasmic-override={overrides.toggle3}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.toggle3)}
                      >
                        <div
                          data-plasmic-name={"divider4"}
                          data-plasmic-override={overrides.divider4}
                          className={classNames(projectcss.all, sty.divider4)}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"titleIcon3"}
                          data-plasmic-override={overrides.titleIcon3}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.titleIcon3)}
                        >
                          <div
                            data-plasmic-name={"howDoesItWork2"}
                            data-plasmic-override={overrides.howDoesItWork2}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.howDoesItWork2
                            )}
                          >
                            {"Dose it suppport Dark Mode"}
                          </div>

                          <IconsArrowDownSimpleLineIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ync29
                            )}
                            role={"img"}
                          />
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"toggle4"}
                        data-plasmic-override={overrides.toggle4}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.toggle4)}
                      >
                        <div
                          data-plasmic-name={"divider5"}
                          data-plasmic-override={overrides.divider5}
                          className={classNames(projectcss.all, sty.divider5)}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"titleIcon4"}
                          data-plasmic-override={overrides.titleIcon4}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.titleIcon4)}
                        >
                          <div
                            data-plasmic-name={"howDoesItWork3"}
                            data-plasmic-override={overrides.howDoesItWork3}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.howDoesItWork3
                            )}
                          >
                            {"Does it support Auto-Layout"}
                          </div>

                          <IconsArrowDownSimpleLineIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___4MC8O
                            )}
                            role={"img"}
                          />
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"toggle5"}
                        data-plasmic-override={overrides.toggle5}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.toggle5)}
                      >
                        <div
                          data-plasmic-name={"divider6"}
                          data-plasmic-override={overrides.divider6}
                          className={classNames(projectcss.all, sty.divider6)}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"titleIcon5"}
                          data-plasmic-override={overrides.titleIcon5}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.titleIcon5)}
                        >
                          <div
                            data-plasmic-name={"howDoesItWork4"}
                            data-plasmic-override={overrides.howDoesItWork4}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.howDoesItWork4
                            )}
                          >
                            {"What is Stacks Design System"}
                          </div>

                          <IconsArrowDownSimpleLineIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kf7GM
                            )}
                            role={"img"}
                          />
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"categories"}
                    data-plasmic-override={overrides.categories}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.categories)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame14"}
                      data-plasmic-override={overrides.frame14}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame14)}
                    >
                      <IconsHomeFilledIcon
                        className={classNames(projectcss.all, sty.svg__dShgc)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mBiDf
                        )}
                      >
                        {"General"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame15"}
                      data-plasmic-override={overrides.frame15}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame15)}
                    >
                      <IconsCircleAndSquareFilledIcon
                        className={classNames(projectcss.all, sty.svg__ti2B)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wcs38
                        )}
                      >
                        {"Support"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame16"}
                      data-plasmic-override={overrides.frame16}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame16)}
                    >
                      <IconsLightningFilledIcon
                        className={classNames(projectcss.all, sty.svg__pbW)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jSr99
                        )}
                      >
                        {"Hosting"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame17"}
                      data-plasmic-override={overrides.frame17}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame17)}
                    >
                      <IconsPenFilledIcon
                        className={classNames(projectcss.all, sty.svg___8VIaz)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4Kjkx
                        )}
                      >
                        {"Product"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"hotBidDesktopLight"}
              data-plasmic-override={overrides.hotBidDesktopLight}
              hasGap={true}
              className={classNames(projectcss.all, sty.hotBidDesktopLight)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame913"}
                data-plasmic-override={overrides.frame913}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame913)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rw5HQ
                  )}
                >
                  {"Popular"}
                </div>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"arrows"}
                  data-plasmic-override={overrides.arrows}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.arrows)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"leftArrow"}
                    data-plasmic-override={overrides.leftArrow}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.leftArrow)}
                  >
                    <IconsArrowLeft2Line3Icon
                      className={classNames(projectcss.all, sty.svg__vg8Jk)}
                      role={"img"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"rightArrow"}
                    data-plasmic-override={overrides.rightArrow}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.rightArrow)}
                  >
                    <IconsArrowRight2Line2Icon
                      className={classNames(projectcss.all, sty.svg__ktpUc)}
                      role={"img"}
                    />
                  </p.Stack>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"row"}
                data-plasmic-override={overrides.row}
                hasGap={true}
                className={classNames(projectcss.all, sty.row)}
              >
                <div
                  data-plasmic-name={"card"}
                  data-plasmic-override={overrides.card}
                  className={classNames(projectcss.all, sty.card)}
                >
                  <div
                    data-plasmic-name={"productImg"}
                    data-plasmic-override={overrides.productImg}
                    className={classNames(projectcss.all, sty.productImg)}
                  >
                    <div
                      data-plasmic-name={"media16"}
                      data-plasmic-override={overrides.media16}
                      className={classNames(projectcss.all, sty.media16)}
                    >
                      <div
                        data-plasmic-name={"imgLibimg132"}
                        data-plasmic-override={overrides.imgLibimg132}
                        className={classNames(projectcss.all, sty.imgLibimg132)}
                      >
                        <div
                          data-plasmic-name={
                            "michaelDziedzicD6FMtY6XCyMUnsplash1"
                          }
                          data-plasmic-override={
                            overrides.michaelDziedzicD6FMtY6XCyMUnsplash1
                          }
                          className={classNames(
                            projectcss.all,
                            sty.michaelDziedzicD6FMtY6XCyMUnsplash1
                          )}
                        />
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"idkAlbumClean111"}
                      data-plasmic-override={overrides.idkAlbumClean111}
                      className={classNames(
                        projectcss.all,
                        sty.idkAlbumClean111
                      )}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"itemInfo"}
                    data-plasmic-override={overrides.itemInfo}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.itemInfo)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice"}
                      data-plasmic-override={overrides.titlePrice}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k1Xf
                        )}
                      >
                        {"USEE4URSELF"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"label3"}
                        data-plasmic-override={overrides.label3}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.label3)}
                      >
                        <div
                          data-plasmic-name={"popular"}
                          data-plasmic-override={overrides.popular}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.popular
                          )}
                        >
                          {"243 SOL"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice2"}
                      data-plasmic-override={overrides.titlePrice2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4VbiC
                        )}
                      >
                        {"IDK"}
                      </div>

                      <div
                        data-plasmic-name={"frame1092"}
                        data-plasmic-override={overrides.frame1092}
                        className={classNames(projectcss.all, sty.frame1092)}
                      >
                        <div
                          data-plasmic-name={"release"}
                          data-plasmic-override={overrides.release}
                          className={classNames(projectcss.all, sty.release)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__coIce
                            )}
                          >
                            {"RELEASE"}
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"highestBid"}
                          data-plasmic-override={overrides.highestBid}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.highestBid)}
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div
                  data-plasmic-name={"card2"}
                  data-plasmic-override={overrides.card2}
                  className={classNames(projectcss.all, sty.card2)}
                >
                  <div
                    data-plasmic-name={"productImg2"}
                    data-plasmic-override={overrides.productImg2}
                    className={classNames(projectcss.all, sty.productImg2)}
                  >
                    <div
                      data-plasmic-name={"media162"}
                      data-plasmic-override={overrides.media162}
                      className={classNames(projectcss.all, sty.media162)}
                    >
                      <div
                        data-plasmic-name={"imgLibimg133"}
                        data-plasmic-override={overrides.imgLibimg133}
                        className={classNames(projectcss.all, sty.imgLibimg133)}
                      >
                        <div
                          data-plasmic-name={
                            "michaelDziedzicD6FMtY6XCyMUnsplash2"
                          }
                          data-plasmic-override={
                            overrides.michaelDziedzicD6FMtY6XCyMUnsplash2
                          }
                          className={classNames(
                            projectcss.all,
                            sty.michaelDziedzicD6FMtY6XCyMUnsplash2
                          )}
                        />
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"idkAlbumClean112"}
                      data-plasmic-override={overrides.idkAlbumClean112}
                      className={classNames(
                        projectcss.all,
                        sty.idkAlbumClean112
                      )}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"itemInfo2"}
                    data-plasmic-override={overrides.itemInfo2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.itemInfo2)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice3"}
                      data-plasmic-override={overrides.titlePrice3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cNuiI
                        )}
                      >
                        {"USEE4URSELF"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"label4"}
                        data-plasmic-override={overrides.label4}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.label4)}
                      >
                        <div
                          data-plasmic-name={"popular2"}
                          data-plasmic-override={overrides.popular2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.popular2
                          )}
                        >
                          {"243 SOL"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice4"}
                      data-plasmic-override={overrides.titlePrice4}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gb6Aa
                        )}
                      >
                        {"IDK"}
                      </div>

                      <div
                        data-plasmic-name={"frame1093"}
                        data-plasmic-override={overrides.frame1093}
                        className={classNames(projectcss.all, sty.frame1093)}
                      >
                        <div
                          data-plasmic-name={"release2"}
                          data-plasmic-override={overrides.release2}
                          className={classNames(projectcss.all, sty.release2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sn5C9
                            )}
                          >
                            {"RELEASE"}
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"highestBid2"}
                          data-plasmic-override={overrides.highestBid2}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.highestBid2
                          )}
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div
                  data-plasmic-name={"card3"}
                  data-plasmic-override={overrides.card3}
                  className={classNames(projectcss.all, sty.card3)}
                >
                  <div
                    data-plasmic-name={"productImg3"}
                    data-plasmic-override={overrides.productImg3}
                    className={classNames(projectcss.all, sty.productImg3)}
                  >
                    <div
                      data-plasmic-name={"media163"}
                      data-plasmic-override={overrides.media163}
                      className={classNames(projectcss.all, sty.media163)}
                    >
                      <div
                        data-plasmic-name={"imgLibimg134"}
                        data-plasmic-override={overrides.imgLibimg134}
                        className={classNames(projectcss.all, sty.imgLibimg134)}
                      >
                        <div
                          data-plasmic-name={
                            "michaelDziedzicD6FMtY6XCyMUnsplash3"
                          }
                          data-plasmic-override={
                            overrides.michaelDziedzicD6FMtY6XCyMUnsplash3
                          }
                          className={classNames(
                            projectcss.all,
                            sty.michaelDziedzicD6FMtY6XCyMUnsplash3
                          )}
                        />
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"idkAlbumClean113"}
                      data-plasmic-override={overrides.idkAlbumClean113}
                      className={classNames(
                        projectcss.all,
                        sty.idkAlbumClean113
                      )}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"itemInfo3"}
                    data-plasmic-override={overrides.itemInfo3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.itemInfo3)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice5"}
                      data-plasmic-override={overrides.titlePrice5}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yEdsJ
                        )}
                      >
                        {"USEE4URSELF"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"label5"}
                        data-plasmic-override={overrides.label5}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.label5)}
                      >
                        <div
                          data-plasmic-name={"popular3"}
                          data-plasmic-override={overrides.popular3}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.popular3
                          )}
                        >
                          {"243 SOL"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice6"}
                      data-plasmic-override={overrides.titlePrice6}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice6)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gzRom
                        )}
                      >
                        {"IDK"}
                      </div>

                      <div
                        data-plasmic-name={"frame1094"}
                        data-plasmic-override={overrides.frame1094}
                        className={classNames(projectcss.all, sty.frame1094)}
                      >
                        <div
                          data-plasmic-name={"release3"}
                          data-plasmic-override={overrides.release3}
                          className={classNames(projectcss.all, sty.release3)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jee8I
                            )}
                          >
                            {"RELEASE"}
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"highestBid3"}
                          data-plasmic-override={overrides.highestBid3}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.highestBid3
                          )}
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div
                  data-plasmic-name={"card4"}
                  data-plasmic-override={overrides.card4}
                  className={classNames(projectcss.all, sty.card4)}
                >
                  <div
                    data-plasmic-name={"productImg4"}
                    data-plasmic-override={overrides.productImg4}
                    className={classNames(projectcss.all, sty.productImg4)}
                  >
                    <div
                      data-plasmic-name={"media164"}
                      data-plasmic-override={overrides.media164}
                      className={classNames(projectcss.all, sty.media164)}
                    >
                      <div
                        data-plasmic-name={"imgLibimg135"}
                        data-plasmic-override={overrides.imgLibimg135}
                        className={classNames(projectcss.all, sty.imgLibimg135)}
                      >
                        <div
                          data-plasmic-name={
                            "michaelDziedzicD6FMtY6XCyMUnsplash4"
                          }
                          data-plasmic-override={
                            overrides.michaelDziedzicD6FMtY6XCyMUnsplash4
                          }
                          className={classNames(
                            projectcss.all,
                            sty.michaelDziedzicD6FMtY6XCyMUnsplash4
                          )}
                        />
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"idkAlbumClean114"}
                      data-plasmic-override={overrides.idkAlbumClean114}
                      className={classNames(
                        projectcss.all,
                        sty.idkAlbumClean114
                      )}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"itemInfo4"}
                    data-plasmic-override={overrides.itemInfo4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.itemInfo4)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice7"}
                      data-plasmic-override={overrides.titlePrice7}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ki4L1
                        )}
                      >
                        {"USEE4URSELF"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"label6"}
                        data-plasmic-override={overrides.label6}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.label6)}
                      >
                        <div
                          data-plasmic-name={"popular4"}
                          data-plasmic-override={overrides.popular4}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.popular4
                          )}
                        >
                          {"243 SOL"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"titlePrice8"}
                      data-plasmic-override={overrides.titlePrice8}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.titlePrice8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4Dz3L
                        )}
                      >
                        {"IDK"}
                      </div>

                      <div
                        data-plasmic-name={"frame1095"}
                        data-plasmic-override={overrides.frame1095}
                        className={classNames(projectcss.all, sty.frame1095)}
                      >
                        <div
                          data-plasmic-name={"release4"}
                          data-plasmic-override={overrides.release4}
                          className={classNames(projectcss.all, sty.release4)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__s178K
                            )}
                          >
                            {"RELEASE"}
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"highestBid4"}
                          data-plasmic-override={overrides.highestBid4}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.highestBid4
                          )}
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>
            </p.Stack>

            <div
              data-plasmic-name={"footerDesktopLight"}
              data-plasmic-override={overrides.footerDesktopLight}
              className={classNames(projectcss.all, sty.footerDesktopLight)}
            >
              <div
                data-plasmic-name={"divider7"}
                data-plasmic-override={overrides.divider7}
                className={classNames(projectcss.all, sty.divider7)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"footer05DesktopLight"}
                data-plasmic-override={overrides.footer05DesktopLight}
                hasGap={true}
                className={classNames(projectcss.all, sty.footer05DesktopLight)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame789"}
                  data-plasmic-override={overrides.frame789}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame789)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame787"}
                    data-plasmic-override={overrides.frame787}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame787)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame774"}
                      data-plasmic-override={overrides.frame774}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame774)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"logo2"}
                        data-plasmic-override={overrides.logo2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.logo2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yWt85
                          )}
                        >
                          {"Paperhouse"}
                        </div>
                      </p.Stack>

                      <div
                        data-plasmic-name={"letsMakeAGreatDesignTogerther"}
                        data-plasmic-override={
                          overrides.letsMakeAGreatDesignTogerther
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.letsMakeAGreatDesignTogerther
                        )}
                      >
                        {"An ecosystem for the new music industry."}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame783"}
                      data-plasmic-override={overrides.frame783}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame783)}
                    >
                      <div
                        data-plasmic-name={"crypter"}
                        data-plasmic-override={overrides.crypter}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.crypter
                        )}
                      >
                        {"From us"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame726"}
                        data-plasmic-override={overrides.frame726}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame726)}
                      >
                        <div
                          data-plasmic-name={"about"}
                          data-plasmic-override={overrides.about}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.about
                          )}
                        >
                          {"Discover"}
                        </div>

                        <div
                          data-plasmic-name={"projects"}
                          data-plasmic-override={overrides.projects}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.projects
                          )}
                        >
                          {"Connect wallet"}
                        </div>

                        <div
                          data-plasmic-name={"whatWeDo"}
                          data-plasmic-override={overrides.whatWeDo}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.whatWeDo
                          )}
                        >
                          {"Create item"}
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xngO1
                            )}
                          >
                            {"Press"}
                          </div>
                        ) : null}
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ivopL
                            )}
                          >
                            {"Jobs"}
                          </div>
                        ) : null}
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame784"}
                      data-plasmic-override={overrides.frame784}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame784)}
                    >
                      <div
                        data-plasmic-name={"info"}
                        data-plasmic-override={overrides.info}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.info
                        )}
                      >
                        {"Resources"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame727"}
                        data-plasmic-override={overrides.frame727}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame727)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rKjE3
                          )}
                        >
                          {"Download"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iAYj
                          )}
                        >
                          {"Demos"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__je3I4
                          )}
                        >
                          {"Support"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    {false ? (
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame786"}
                        data-plasmic-override={overrides.frame786}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame786)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hCji
                          )}
                        >
                          {"Join Newsletter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame785"}
                          data-plasmic-override={overrides.frame785}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame785)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__w4OYr
                            )}
                          >
                            {
                              "Subscribe our newsletter to get more free design course and resource"
                            }
                          </div>

                          <div
                            data-plasmic-name={"singleInputField"}
                            data-plasmic-override={overrides.singleInputField}
                            className={classNames(
                              projectcss.all,
                              sty.singleInputField
                            )}
                          >
                            <div
                              data-plasmic-name={"enterYourEmail"}
                              data-plasmic-override={overrides.enterYourEmail}
                              className={classNames(
                                projectcss.all,
                                sty.enterYourEmail
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__oqUiU
                                )}
                              >
                                {"Enter your email"}
                              </div>
                            </div>

                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"smallCircleButton"}
                              data-plasmic-override={
                                overrides.smallCircleButton
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.smallCircleButton
                              )}
                            >
                              <IconsArrowRight2Line2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__flkQg
                                )}
                                role={"img"}
                              />
                            </p.Stack>
                          </div>
                        </p.Stack>
                      </p.Stack>
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"bottomBar"}
                    data-plasmic-override={overrides.bottomBar}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.bottomBar)}
                  >
                    <div
                      data-plasmic-name={"divider8"}
                      data-plasmic-override={overrides.divider8}
                      className={classNames(projectcss.all, sty.divider8)}
                    />

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"bottomBarContent"}
                      data-plasmic-override={overrides.bottomBarContent}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.bottomBarContent
                      )}
                    >
                      <div
                        data-plasmic-name={
                          "copyright2021Ui8LlcAllRightsReserved"
                        }
                        data-plasmic-override={
                          overrides.copyright2021Ui8LlcAllRightsReserved
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.copyright2021Ui8LlcAllRightsReserved
                        )}
                      >
                        {
                          "Copyright © 2021 Paperhouse LLC. All rights reserved."
                        }
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame788"}
                        data-plasmic-override={overrides.frame788}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame788)}
                      >
                        <div
                          data-plasmic-name={"weUseCookiesForBetterService"}
                          data-plasmic-override={
                            overrides.weUseCookiesForBetterService
                          }
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.weUseCookiesForBetterService
                          )}
                        >
                          {"We’re hiring!"}
                        </div>

                        <div
                          data-plasmic-name={"accept"}
                          data-plasmic-override={overrides.accept}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.accept
                          )}
                        >
                          {"Apply"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "faqDesktopLight",
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2",
    "faq02DesktopLight",
    "frame20",
    "frame5",
    "frame4",
    "frame19",
    "frame22",
    "frame11",
    "toggle",
    "divider2",
    "titleIcon",
    "frame21",
    "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode",
    "buttons2",
    "contactUs",
    "frame12",
    "toggle2",
    "divider3",
    "titleIcon2",
    "howDoesItWork",
    "toggle3",
    "divider4",
    "titleIcon3",
    "howDoesItWork2",
    "toggle4",
    "divider5",
    "titleIcon4",
    "howDoesItWork3",
    "toggle5",
    "divider6",
    "titleIcon5",
    "howDoesItWork4",
    "categories",
    "frame14",
    "frame15",
    "frame16",
    "frame17",
    "hotBidDesktopLight",
    "frame913",
    "arrows",
    "leftArrow",
    "rightArrow",
    "row",
    "card",
    "productImg",
    "media16",
    "imgLibimg132",
    "michaelDziedzicD6FMtY6XCyMUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "label3",
    "popular",
    "titlePrice2",
    "frame1092",
    "release",
    "highestBid",
    "card2",
    "productImg2",
    "media162",
    "imgLibimg133",
    "michaelDziedzicD6FMtY6XCyMUnsplash2",
    "idkAlbumClean112",
    "itemInfo2",
    "titlePrice3",
    "label4",
    "popular2",
    "titlePrice4",
    "frame1093",
    "release2",
    "highestBid2",
    "card3",
    "productImg3",
    "media163",
    "imgLibimg134",
    "michaelDziedzicD6FMtY6XCyMUnsplash3",
    "idkAlbumClean113",
    "itemInfo3",
    "titlePrice5",
    "label5",
    "popular3",
    "titlePrice6",
    "frame1094",
    "release3",
    "highestBid3",
    "card4",
    "productImg4",
    "media164",
    "imgLibimg135",
    "michaelDziedzicD6FMtY6XCyMUnsplash4",
    "idkAlbumClean114",
    "itemInfo4",
    "titlePrice7",
    "label6",
    "popular4",
    "titlePrice8",
    "frame1095",
    "release4",
    "highestBid4",
    "footerDesktopLight",
    "divider7",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider8",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  faqDesktopLight: [
    "faqDesktopLight",
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2",
    "faq02DesktopLight",
    "frame20",
    "frame5",
    "frame4",
    "frame19",
    "frame22",
    "frame11",
    "toggle",
    "divider2",
    "titleIcon",
    "frame21",
    "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode",
    "buttons2",
    "contactUs",
    "frame12",
    "toggle2",
    "divider3",
    "titleIcon2",
    "howDoesItWork",
    "toggle3",
    "divider4",
    "titleIcon3",
    "howDoesItWork2",
    "toggle4",
    "divider5",
    "titleIcon4",
    "howDoesItWork3",
    "toggle5",
    "divider6",
    "titleIcon5",
    "howDoesItWork4",
    "categories",
    "frame14",
    "frame15",
    "frame16",
    "frame17",
    "hotBidDesktopLight",
    "frame913",
    "arrows",
    "leftArrow",
    "rightArrow",
    "row",
    "card",
    "productImg",
    "media16",
    "imgLibimg132",
    "michaelDziedzicD6FMtY6XCyMUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "label3",
    "popular",
    "titlePrice2",
    "frame1092",
    "release",
    "highestBid",
    "card2",
    "productImg2",
    "media162",
    "imgLibimg133",
    "michaelDziedzicD6FMtY6XCyMUnsplash2",
    "idkAlbumClean112",
    "itemInfo2",
    "titlePrice3",
    "label4",
    "popular2",
    "titlePrice4",
    "frame1093",
    "release2",
    "highestBid2",
    "card3",
    "productImg3",
    "media163",
    "imgLibimg134",
    "michaelDziedzicD6FMtY6XCyMUnsplash3",
    "idkAlbumClean113",
    "itemInfo3",
    "titlePrice5",
    "label5",
    "popular3",
    "titlePrice6",
    "frame1094",
    "release3",
    "highestBid3",
    "card4",
    "productImg4",
    "media164",
    "imgLibimg135",
    "michaelDziedzicD6FMtY6XCyMUnsplash4",
    "idkAlbumClean114",
    "itemInfo4",
    "titlePrice7",
    "label6",
    "popular4",
    "titlePrice8",
    "frame1095",
    "release4",
    "highestBid4",
    "footerDesktopLight",
    "divider7",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider8",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  navDefaultDesktopLight: [
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2"
  ],

  navContent: [
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2"
  ],

  leftContent: ["leftContent", "logo", "divider"],
  logo: ["logo"],
  divider: ["divider"],
  actions: ["actions", "buttons", "button", "label", "button2", "label2"],
  buttons: ["buttons", "button", "label", "button2", "label2"],
  button: ["button", "label"],
  label: ["label"],
  button2: ["button2", "label2"],
  label2: ["label2"],
  faq02DesktopLight: [
    "faq02DesktopLight",
    "frame20",
    "frame5",
    "frame4",
    "frame19",
    "frame22",
    "frame11",
    "toggle",
    "divider2",
    "titleIcon",
    "frame21",
    "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode",
    "buttons2",
    "contactUs",
    "frame12",
    "toggle2",
    "divider3",
    "titleIcon2",
    "howDoesItWork",
    "toggle3",
    "divider4",
    "titleIcon3",
    "howDoesItWork2",
    "toggle4",
    "divider5",
    "titleIcon4",
    "howDoesItWork3",
    "toggle5",
    "divider6",
    "titleIcon5",
    "howDoesItWork4",
    "categories",
    "frame14",
    "frame15",
    "frame16",
    "frame17"
  ],

  frame20: [
    "frame20",
    "frame5",
    "frame4",
    "frame19",
    "frame22",
    "frame11",
    "toggle",
    "divider2",
    "titleIcon",
    "frame21",
    "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode",
    "buttons2",
    "contactUs",
    "frame12",
    "toggle2",
    "divider3",
    "titleIcon2",
    "howDoesItWork",
    "toggle3",
    "divider4",
    "titleIcon3",
    "howDoesItWork2",
    "toggle4",
    "divider5",
    "titleIcon4",
    "howDoesItWork3",
    "toggle5",
    "divider6",
    "titleIcon5",
    "howDoesItWork4",
    "categories",
    "frame14",
    "frame15",
    "frame16",
    "frame17"
  ],

  frame5: ["frame5", "frame4"],
  frame4: ["frame4"],
  frame19: [
    "frame19",
    "frame22",
    "frame11",
    "toggle",
    "divider2",
    "titleIcon",
    "frame21",
    "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode",
    "buttons2",
    "contactUs",
    "frame12",
    "toggle2",
    "divider3",
    "titleIcon2",
    "howDoesItWork",
    "toggle3",
    "divider4",
    "titleIcon3",
    "howDoesItWork2",
    "toggle4",
    "divider5",
    "titleIcon4",
    "howDoesItWork3",
    "toggle5",
    "divider6",
    "titleIcon5",
    "howDoesItWork4",
    "categories",
    "frame14",
    "frame15",
    "frame16",
    "frame17"
  ],

  frame22: [
    "frame22",
    "frame11",
    "toggle",
    "divider2",
    "titleIcon",
    "frame21",
    "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode",
    "buttons2",
    "contactUs",
    "frame12",
    "toggle2",
    "divider3",
    "titleIcon2",
    "howDoesItWork",
    "toggle3",
    "divider4",
    "titleIcon3",
    "howDoesItWork2",
    "toggle4",
    "divider5",
    "titleIcon4",
    "howDoesItWork3",
    "toggle5",
    "divider6",
    "titleIcon5",
    "howDoesItWork4"
  ],

  frame11: ["frame11", "toggle", "divider2", "titleIcon"],
  toggle: ["toggle", "divider2", "titleIcon"],
  divider2: ["divider2"],
  titleIcon: ["titleIcon"],
  frame21: [
    "frame21",
    "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode",
    "buttons2",
    "contactUs"
  ],

  theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode:
    [
      "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode"
    ],

  buttons2: ["buttons2", "contactUs"],
  contactUs: ["contactUs"],
  frame12: [
    "frame12",
    "toggle2",
    "divider3",
    "titleIcon2",
    "howDoesItWork",
    "toggle3",
    "divider4",
    "titleIcon3",
    "howDoesItWork2",
    "toggle4",
    "divider5",
    "titleIcon4",
    "howDoesItWork3",
    "toggle5",
    "divider6",
    "titleIcon5",
    "howDoesItWork4"
  ],

  toggle2: ["toggle2", "divider3", "titleIcon2", "howDoesItWork"],
  divider3: ["divider3"],
  titleIcon2: ["titleIcon2", "howDoesItWork"],
  howDoesItWork: ["howDoesItWork"],
  toggle3: ["toggle3", "divider4", "titleIcon3", "howDoesItWork2"],
  divider4: ["divider4"],
  titleIcon3: ["titleIcon3", "howDoesItWork2"],
  howDoesItWork2: ["howDoesItWork2"],
  toggle4: ["toggle4", "divider5", "titleIcon4", "howDoesItWork3"],
  divider5: ["divider5"],
  titleIcon4: ["titleIcon4", "howDoesItWork3"],
  howDoesItWork3: ["howDoesItWork3"],
  toggle5: ["toggle5", "divider6", "titleIcon5", "howDoesItWork4"],
  divider6: ["divider6"],
  titleIcon5: ["titleIcon5", "howDoesItWork4"],
  howDoesItWork4: ["howDoesItWork4"],
  categories: ["categories", "frame14", "frame15", "frame16", "frame17"],
  frame14: ["frame14"],
  frame15: ["frame15"],
  frame16: ["frame16"],
  frame17: ["frame17"],
  hotBidDesktopLight: [
    "hotBidDesktopLight",
    "frame913",
    "arrows",
    "leftArrow",
    "rightArrow",
    "row",
    "card",
    "productImg",
    "media16",
    "imgLibimg132",
    "michaelDziedzicD6FMtY6XCyMUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "label3",
    "popular",
    "titlePrice2",
    "frame1092",
    "release",
    "highestBid",
    "card2",
    "productImg2",
    "media162",
    "imgLibimg133",
    "michaelDziedzicD6FMtY6XCyMUnsplash2",
    "idkAlbumClean112",
    "itemInfo2",
    "titlePrice3",
    "label4",
    "popular2",
    "titlePrice4",
    "frame1093",
    "release2",
    "highestBid2",
    "card3",
    "productImg3",
    "media163",
    "imgLibimg134",
    "michaelDziedzicD6FMtY6XCyMUnsplash3",
    "idkAlbumClean113",
    "itemInfo3",
    "titlePrice5",
    "label5",
    "popular3",
    "titlePrice6",
    "frame1094",
    "release3",
    "highestBid3",
    "card4",
    "productImg4",
    "media164",
    "imgLibimg135",
    "michaelDziedzicD6FMtY6XCyMUnsplash4",
    "idkAlbumClean114",
    "itemInfo4",
    "titlePrice7",
    "label6",
    "popular4",
    "titlePrice8",
    "frame1095",
    "release4",
    "highestBid4"
  ],

  frame913: ["frame913", "arrows", "leftArrow", "rightArrow"],
  arrows: ["arrows", "leftArrow", "rightArrow"],
  leftArrow: ["leftArrow"],
  rightArrow: ["rightArrow"],
  row: [
    "row",
    "card",
    "productImg",
    "media16",
    "imgLibimg132",
    "michaelDziedzicD6FMtY6XCyMUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "label3",
    "popular",
    "titlePrice2",
    "frame1092",
    "release",
    "highestBid",
    "card2",
    "productImg2",
    "media162",
    "imgLibimg133",
    "michaelDziedzicD6FMtY6XCyMUnsplash2",
    "idkAlbumClean112",
    "itemInfo2",
    "titlePrice3",
    "label4",
    "popular2",
    "titlePrice4",
    "frame1093",
    "release2",
    "highestBid2",
    "card3",
    "productImg3",
    "media163",
    "imgLibimg134",
    "michaelDziedzicD6FMtY6XCyMUnsplash3",
    "idkAlbumClean113",
    "itemInfo3",
    "titlePrice5",
    "label5",
    "popular3",
    "titlePrice6",
    "frame1094",
    "release3",
    "highestBid3",
    "card4",
    "productImg4",
    "media164",
    "imgLibimg135",
    "michaelDziedzicD6FMtY6XCyMUnsplash4",
    "idkAlbumClean114",
    "itemInfo4",
    "titlePrice7",
    "label6",
    "popular4",
    "titlePrice8",
    "frame1095",
    "release4",
    "highestBid4"
  ],

  card: [
    "card",
    "productImg",
    "media16",
    "imgLibimg132",
    "michaelDziedzicD6FMtY6XCyMUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "label3",
    "popular",
    "titlePrice2",
    "frame1092",
    "release",
    "highestBid"
  ],

  productImg: [
    "productImg",
    "media16",
    "imgLibimg132",
    "michaelDziedzicD6FMtY6XCyMUnsplash1",
    "idkAlbumClean111"
  ],

  media16: ["media16", "imgLibimg132", "michaelDziedzicD6FMtY6XCyMUnsplash1"],
  imgLibimg132: ["imgLibimg132", "michaelDziedzicD6FMtY6XCyMUnsplash1"],
  michaelDziedzicD6FMtY6XCyMUnsplash1: ["michaelDziedzicD6FMtY6XCyMUnsplash1"],
  idkAlbumClean111: ["idkAlbumClean111"],
  itemInfo: [
    "itemInfo",
    "titlePrice",
    "label3",
    "popular",
    "titlePrice2",
    "frame1092",
    "release",
    "highestBid"
  ],

  titlePrice: ["titlePrice", "label3", "popular"],
  label3: ["label3", "popular"],
  popular: ["popular"],
  titlePrice2: ["titlePrice2", "frame1092", "release", "highestBid"],
  frame1092: ["frame1092", "release", "highestBid"],
  release: ["release"],
  highestBid: ["highestBid"],
  card2: [
    "card2",
    "productImg2",
    "media162",
    "imgLibimg133",
    "michaelDziedzicD6FMtY6XCyMUnsplash2",
    "idkAlbumClean112",
    "itemInfo2",
    "titlePrice3",
    "label4",
    "popular2",
    "titlePrice4",
    "frame1093",
    "release2",
    "highestBid2"
  ],

  productImg2: [
    "productImg2",
    "media162",
    "imgLibimg133",
    "michaelDziedzicD6FMtY6XCyMUnsplash2",
    "idkAlbumClean112"
  ],

  media162: ["media162", "imgLibimg133", "michaelDziedzicD6FMtY6XCyMUnsplash2"],
  imgLibimg133: ["imgLibimg133", "michaelDziedzicD6FMtY6XCyMUnsplash2"],
  michaelDziedzicD6FMtY6XCyMUnsplash2: ["michaelDziedzicD6FMtY6XCyMUnsplash2"],
  idkAlbumClean112: ["idkAlbumClean112"],
  itemInfo2: [
    "itemInfo2",
    "titlePrice3",
    "label4",
    "popular2",
    "titlePrice4",
    "frame1093",
    "release2",
    "highestBid2"
  ],

  titlePrice3: ["titlePrice3", "label4", "popular2"],
  label4: ["label4", "popular2"],
  popular2: ["popular2"],
  titlePrice4: ["titlePrice4", "frame1093", "release2", "highestBid2"],
  frame1093: ["frame1093", "release2", "highestBid2"],
  release2: ["release2"],
  highestBid2: ["highestBid2"],
  card3: [
    "card3",
    "productImg3",
    "media163",
    "imgLibimg134",
    "michaelDziedzicD6FMtY6XCyMUnsplash3",
    "idkAlbumClean113",
    "itemInfo3",
    "titlePrice5",
    "label5",
    "popular3",
    "titlePrice6",
    "frame1094",
    "release3",
    "highestBid3"
  ],

  productImg3: [
    "productImg3",
    "media163",
    "imgLibimg134",
    "michaelDziedzicD6FMtY6XCyMUnsplash3",
    "idkAlbumClean113"
  ],

  media163: ["media163", "imgLibimg134", "michaelDziedzicD6FMtY6XCyMUnsplash3"],
  imgLibimg134: ["imgLibimg134", "michaelDziedzicD6FMtY6XCyMUnsplash3"],
  michaelDziedzicD6FMtY6XCyMUnsplash3: ["michaelDziedzicD6FMtY6XCyMUnsplash3"],
  idkAlbumClean113: ["idkAlbumClean113"],
  itemInfo3: [
    "itemInfo3",
    "titlePrice5",
    "label5",
    "popular3",
    "titlePrice6",
    "frame1094",
    "release3",
    "highestBid3"
  ],

  titlePrice5: ["titlePrice5", "label5", "popular3"],
  label5: ["label5", "popular3"],
  popular3: ["popular3"],
  titlePrice6: ["titlePrice6", "frame1094", "release3", "highestBid3"],
  frame1094: ["frame1094", "release3", "highestBid3"],
  release3: ["release3"],
  highestBid3: ["highestBid3"],
  card4: [
    "card4",
    "productImg4",
    "media164",
    "imgLibimg135",
    "michaelDziedzicD6FMtY6XCyMUnsplash4",
    "idkAlbumClean114",
    "itemInfo4",
    "titlePrice7",
    "label6",
    "popular4",
    "titlePrice8",
    "frame1095",
    "release4",
    "highestBid4"
  ],

  productImg4: [
    "productImg4",
    "media164",
    "imgLibimg135",
    "michaelDziedzicD6FMtY6XCyMUnsplash4",
    "idkAlbumClean114"
  ],

  media164: ["media164", "imgLibimg135", "michaelDziedzicD6FMtY6XCyMUnsplash4"],
  imgLibimg135: ["imgLibimg135", "michaelDziedzicD6FMtY6XCyMUnsplash4"],
  michaelDziedzicD6FMtY6XCyMUnsplash4: ["michaelDziedzicD6FMtY6XCyMUnsplash4"],
  idkAlbumClean114: ["idkAlbumClean114"],
  itemInfo4: [
    "itemInfo4",
    "titlePrice7",
    "label6",
    "popular4",
    "titlePrice8",
    "frame1095",
    "release4",
    "highestBid4"
  ],

  titlePrice7: ["titlePrice7", "label6", "popular4"],
  label6: ["label6", "popular4"],
  popular4: ["popular4"],
  titlePrice8: ["titlePrice8", "frame1095", "release4", "highestBid4"],
  frame1095: ["frame1095", "release4", "highestBid4"],
  release4: ["release4"],
  highestBid4: ["highestBid4"],
  footerDesktopLight: [
    "footerDesktopLight",
    "divider7",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider8",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider7: ["divider7"],
  footer05DesktopLight: [
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider8",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame789: [
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider8",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame787: [
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame774: ["frame774", "logo2", "letsMakeAGreatDesignTogerther"],
  logo2: ["logo2"],
  letsMakeAGreatDesignTogerther: ["letsMakeAGreatDesignTogerther"],
  frame783: [
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo"
  ],

  crypter: ["crypter"],
  frame726: ["frame726", "about", "projects", "whatWeDo"],
  about: ["about"],
  projects: ["projects"],
  whatWeDo: ["whatWeDo"],
  frame784: ["frame784", "info", "frame727"],
  info: ["info"],
  frame727: ["frame727"],
  frame786: [
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame785: [
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  singleInputField: ["singleInputField", "enterYourEmail", "smallCircleButton"],
  enterYourEmail: ["enterYourEmail"],
  smallCircleButton: ["smallCircleButton"],
  bottomBar: [
    "bottomBar",
    "divider8",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider8: ["divider8"],
  bottomBarContent: [
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  copyright2021Ui8LlcAllRightsReserved: [
    "copyright2021Ui8LlcAllRightsReserved"
  ],

  frame788: ["frame788", "weUseCookiesForBetterService", "accept"],
  weUseCookiesForBetterService: ["weUseCookiesForBetterService"],
  accept: ["accept"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFaq__ArgProps,
      internalVariantPropNames: PlasmicFaq__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFaq__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaq";
  } else {
    func.displayName = `PlasmicFaq.${nodeName}`;
  }
  return func;
}

export const PlasmicFaq = Object.assign(
  // Top-level PlasmicFaq renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    faqDesktopLight: makeNodeComponent("faqDesktopLight"),
    navDefaultDesktopLight: makeNodeComponent("navDefaultDesktopLight"),
    navContent: makeNodeComponent("navContent"),
    leftContent: makeNodeComponent("leftContent"),
    logo: makeNodeComponent("logo"),
    divider: makeNodeComponent("divider"),
    actions: makeNodeComponent("actions"),
    buttons: makeNodeComponent("buttons"),
    button: makeNodeComponent("button"),
    label: makeNodeComponent("label"),
    button2: makeNodeComponent("button2"),
    label2: makeNodeComponent("label2"),
    faq02DesktopLight: makeNodeComponent("faq02DesktopLight"),
    frame20: makeNodeComponent("frame20"),
    frame5: makeNodeComponent("frame5"),
    frame4: makeNodeComponent("frame4"),
    frame19: makeNodeComponent("frame19"),
    frame22: makeNodeComponent("frame22"),
    frame11: makeNodeComponent("frame11"),
    toggle: makeNodeComponent("toggle"),
    divider2: makeNodeComponent("divider2"),
    titleIcon: makeNodeComponent("titleIcon"),
    frame21: makeNodeComponent("frame21"),
    theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode:
      makeNodeComponent(
        "theStacksSeriesOfProductsStacksLandingPageKitStacksPortfolioKitStacksECommerceKitStacksIsAProductionReadyLibraryOfStackableContentBlocksBuiltInReactNativeMixAndMatchDozensOfResponsiveElementsToQuicklyConfigureYourFavoriteLandingPageLayoutsOrHitTheGroundRunningWith10PreBuiltTemplatesAllInLightOrDarkMode"
      ),

    buttons2: makeNodeComponent("buttons2"),
    contactUs: makeNodeComponent("contactUs"),
    frame12: makeNodeComponent("frame12"),
    toggle2: makeNodeComponent("toggle2"),
    divider3: makeNodeComponent("divider3"),
    titleIcon2: makeNodeComponent("titleIcon2"),
    howDoesItWork: makeNodeComponent("howDoesItWork"),
    toggle3: makeNodeComponent("toggle3"),
    divider4: makeNodeComponent("divider4"),
    titleIcon3: makeNodeComponent("titleIcon3"),
    howDoesItWork2: makeNodeComponent("howDoesItWork2"),
    toggle4: makeNodeComponent("toggle4"),
    divider5: makeNodeComponent("divider5"),
    titleIcon4: makeNodeComponent("titleIcon4"),
    howDoesItWork3: makeNodeComponent("howDoesItWork3"),
    toggle5: makeNodeComponent("toggle5"),
    divider6: makeNodeComponent("divider6"),
    titleIcon5: makeNodeComponent("titleIcon5"),
    howDoesItWork4: makeNodeComponent("howDoesItWork4"),
    categories: makeNodeComponent("categories"),
    frame14: makeNodeComponent("frame14"),
    frame15: makeNodeComponent("frame15"),
    frame16: makeNodeComponent("frame16"),
    frame17: makeNodeComponent("frame17"),
    hotBidDesktopLight: makeNodeComponent("hotBidDesktopLight"),
    frame913: makeNodeComponent("frame913"),
    arrows: makeNodeComponent("arrows"),
    leftArrow: makeNodeComponent("leftArrow"),
    rightArrow: makeNodeComponent("rightArrow"),
    row: makeNodeComponent("row"),
    card: makeNodeComponent("card"),
    productImg: makeNodeComponent("productImg"),
    media16: makeNodeComponent("media16"),
    imgLibimg132: makeNodeComponent("imgLibimg132"),
    michaelDziedzicD6FMtY6XCyMUnsplash1: makeNodeComponent(
      "michaelDziedzicD6FMtY6XCyMUnsplash1"
    ),

    idkAlbumClean111: makeNodeComponent("idkAlbumClean111"),
    itemInfo: makeNodeComponent("itemInfo"),
    titlePrice: makeNodeComponent("titlePrice"),
    label3: makeNodeComponent("label3"),
    popular: makeNodeComponent("popular"),
    titlePrice2: makeNodeComponent("titlePrice2"),
    frame1092: makeNodeComponent("frame1092"),
    release: makeNodeComponent("release"),
    highestBid: makeNodeComponent("highestBid"),
    card2: makeNodeComponent("card2"),
    productImg2: makeNodeComponent("productImg2"),
    media162: makeNodeComponent("media162"),
    imgLibimg133: makeNodeComponent("imgLibimg133"),
    michaelDziedzicD6FMtY6XCyMUnsplash2: makeNodeComponent(
      "michaelDziedzicD6FMtY6XCyMUnsplash2"
    ),

    idkAlbumClean112: makeNodeComponent("idkAlbumClean112"),
    itemInfo2: makeNodeComponent("itemInfo2"),
    titlePrice3: makeNodeComponent("titlePrice3"),
    label4: makeNodeComponent("label4"),
    popular2: makeNodeComponent("popular2"),
    titlePrice4: makeNodeComponent("titlePrice4"),
    frame1093: makeNodeComponent("frame1093"),
    release2: makeNodeComponent("release2"),
    highestBid2: makeNodeComponent("highestBid2"),
    card3: makeNodeComponent("card3"),
    productImg3: makeNodeComponent("productImg3"),
    media163: makeNodeComponent("media163"),
    imgLibimg134: makeNodeComponent("imgLibimg134"),
    michaelDziedzicD6FMtY6XCyMUnsplash3: makeNodeComponent(
      "michaelDziedzicD6FMtY6XCyMUnsplash3"
    ),

    idkAlbumClean113: makeNodeComponent("idkAlbumClean113"),
    itemInfo3: makeNodeComponent("itemInfo3"),
    titlePrice5: makeNodeComponent("titlePrice5"),
    label5: makeNodeComponent("label5"),
    popular3: makeNodeComponent("popular3"),
    titlePrice6: makeNodeComponent("titlePrice6"),
    frame1094: makeNodeComponent("frame1094"),
    release3: makeNodeComponent("release3"),
    highestBid3: makeNodeComponent("highestBid3"),
    card4: makeNodeComponent("card4"),
    productImg4: makeNodeComponent("productImg4"),
    media164: makeNodeComponent("media164"),
    imgLibimg135: makeNodeComponent("imgLibimg135"),
    michaelDziedzicD6FMtY6XCyMUnsplash4: makeNodeComponent(
      "michaelDziedzicD6FMtY6XCyMUnsplash4"
    ),

    idkAlbumClean114: makeNodeComponent("idkAlbumClean114"),
    itemInfo4: makeNodeComponent("itemInfo4"),
    titlePrice7: makeNodeComponent("titlePrice7"),
    label6: makeNodeComponent("label6"),
    popular4: makeNodeComponent("popular4"),
    titlePrice8: makeNodeComponent("titlePrice8"),
    frame1095: makeNodeComponent("frame1095"),
    release4: makeNodeComponent("release4"),
    highestBid4: makeNodeComponent("highestBid4"),
    footerDesktopLight: makeNodeComponent("footerDesktopLight"),
    divider7: makeNodeComponent("divider7"),
    footer05DesktopLight: makeNodeComponent("footer05DesktopLight"),
    frame789: makeNodeComponent("frame789"),
    frame787: makeNodeComponent("frame787"),
    frame774: makeNodeComponent("frame774"),
    logo2: makeNodeComponent("logo2"),
    letsMakeAGreatDesignTogerther: makeNodeComponent(
      "letsMakeAGreatDesignTogerther"
    ),

    frame783: makeNodeComponent("frame783"),
    crypter: makeNodeComponent("crypter"),
    frame726: makeNodeComponent("frame726"),
    about: makeNodeComponent("about"),
    projects: makeNodeComponent("projects"),
    whatWeDo: makeNodeComponent("whatWeDo"),
    frame784: makeNodeComponent("frame784"),
    info: makeNodeComponent("info"),
    frame727: makeNodeComponent("frame727"),
    frame786: makeNodeComponent("frame786"),
    frame785: makeNodeComponent("frame785"),
    singleInputField: makeNodeComponent("singleInputField"),
    enterYourEmail: makeNodeComponent("enterYourEmail"),
    smallCircleButton: makeNodeComponent("smallCircleButton"),
    bottomBar: makeNodeComponent("bottomBar"),
    divider8: makeNodeComponent("divider8"),
    bottomBarContent: makeNodeComponent("bottomBarContent"),
    copyright2021Ui8LlcAllRightsReserved: makeNodeComponent(
      "copyright2021Ui8LlcAllRightsReserved"
    ),

    frame788: makeNodeComponent("frame788"),
    weUseCookiesForBetterService: makeNodeComponent(
      "weUseCookiesForBetterService"
    ),

    accept: makeNodeComponent("accept"),
    // Metadata about props expected for PlasmicFaq
    internalVariantProps: PlasmicFaq__VariantProps,
    internalArgProps: PlasmicFaq__ArgProps
  }
);

export default PlasmicFaq;
/* prettier-ignore-end */
