// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 73KhD343S1ps4YNpRNR2Mg
// Component: ychE-SK3s4
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_paper_house.module.css"; // plasmic-import: 73KhD343S1ps4YNpRNR2Mg/projectcss
import sty from "./PlasmicConnectWallet.module.css"; // plasmic-import: ychE-SK3s4/css
import IconsArrowLeft2LineIcon from "./icons/PlasmicIcon__IconsArrowLeft2Line"; // plasmic-import: JwqTvGkc8V3/icon
import IconsWalletLineIcon from "./icons/PlasmicIcon__IconsWalletLine"; // plasmic-import: AsHTec35ur9/icon
import IconsCheckLineIcon from "./icons/PlasmicIcon__IconsCheckLine"; // plasmic-import: hel9cvPJoUS/icon
import IconsArrowRight2Line2Icon from "./icons/PlasmicIcon__IconsArrowRight2Line2"; // plasmic-import: ojVcl76mJo1/icon
import IconsCheckLine2Icon from "./icons/PlasmicIcon__IconsCheckLine2"; // plasmic-import: 4yLlpNzl8SJ/icon

export const PlasmicConnectWallet__VariantProps = new Array();

export const PlasmicConnectWallet__ArgProps = new Array();

function PlasmicConnectWallet__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"connectWallet03DesktopLight"}
            data-plasmic-override={overrides.connectWallet03DesktopLight}
            className={classNames(
              projectcss.all,
              sty.connectWallet03DesktopLight
            )}
          >
            <div
              data-plasmic-name={"navDefaultDesktopLight"}
              data-plasmic-override={overrides.navDefaultDesktopLight}
              className={classNames(projectcss.all, sty.navDefaultDesktopLight)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"navContent"}
                data-plasmic-override={overrides.navContent}
                hasGap={true}
                className={classNames(projectcss.all, sty.navContent)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"leftContent"}
                  data-plasmic-override={overrides.leftContent}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.leftContent)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"logo"}
                    data-plasmic-override={overrides.logo}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.logo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rE2Ff
                      )}
                    >
                      {"Paperhouse"}
                    </div>
                  </p.Stack>

                  <div
                    data-plasmic-name={"divider"}
                    data-plasmic-override={overrides.divider}
                    className={classNames(projectcss.all, sty.divider)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nDyvm
                    )}
                  >
                    {"Search"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vwLin
                    )}
                  >
                    {"How it works"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"actions"}
                  data-plasmic-override={overrides.actions}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.actions)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttons"}
                    data-plasmic-override={overrides.buttons}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttons)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button)}
                    >
                      <div
                        data-plasmic-name={"label"}
                        data-plasmic-override={overrides.label}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label
                        )}
                      >
                        {"Create"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button2)}
                    >
                      <div
                        data-plasmic-name={"label2"}
                        data-plasmic-override={overrides.label2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label2
                        )}
                      >
                        {"Open collection"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"connectWallet03DesktopLight2"}
              data-plasmic-override={overrides.connectWallet03DesktopLight2}
              hasGap={true}
              className={classNames(
                projectcss.all,
                sty.connectWallet03DesktopLight2
              )}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                hasGap={true}
                className={classNames(projectcss.all, sty.title)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame924"}
                  data-plasmic-override={overrides.frame924}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame924)}
                >
                  <IconsArrowLeft2LineIcon
                    className={classNames(projectcss.all, sty.svg__a0U91)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u8ZiI
                    )}
                  >
                    {"Connect your wallet"}
                  </div>
                </p.Stack>

                <div
                  data-plasmic-name={"divider2"}
                  data-plasmic-override={overrides.divider2}
                  className={classNames(projectcss.all, sty.divider2)}
                />
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame923"}
                data-plasmic-override={overrides.frame923}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame923)}
              >
                <div
                  data-plasmic-name={"walletList"}
                  data-plasmic-override={overrides.walletList}
                  className={classNames(projectcss.all, sty.walletList)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"walletLabel"}
                    data-plasmic-override={overrides.walletLabel}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.walletLabel)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame920"}
                      data-plasmic-override={overrides.frame920}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame920)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"icon"}
                        data-plasmic-override={overrides.icon}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.icon)}
                      >
                        <IconsWalletLineIcon
                          className={classNames(projectcss.all, sty.svg__h5Y9L)}
                          role={"img"}
                        />
                      </p.Stack>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uqXx
                        )}
                      >
                        {"Coinbase Wallet"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"walletLabel2"}
                    data-plasmic-override={overrides.walletLabel2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.walletLabel2)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame921"}
                      data-plasmic-override={overrides.frame921}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame921)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"icon2"}
                        data-plasmic-override={overrides.icon2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.icon2)}
                      >
                        <IconsCheckLineIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___8On7U
                          )}
                          role={"img"}
                        />
                      </p.Stack>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rpYqm
                        )}
                      >
                        {"Coinbase Wallet"}
                      </div>
                    </p.Stack>

                    <IconsArrowRight2Line2Icon
                      className={classNames(projectcss.all, sty.svg__w2V33)}
                      role={"img"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"walletLabel3"}
                    data-plasmic-override={overrides.walletLabel3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.walletLabel3)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame922"}
                      data-plasmic-override={overrides.frame922}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame922)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"icon3"}
                        data-plasmic-override={overrides.icon3}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.icon3)}
                      >
                        <IconsWalletLineIcon
                          className={classNames(projectcss.all, sty.svg__hHmu7)}
                          role={"img"}
                        />
                      </p.Stack>

                      <div
                        data-plasmic-name={"coinbaseWallet"}
                        data-plasmic-override={overrides.coinbaseWallet}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.coinbaseWallet
                        )}
                      >
                        {"MyEtherWallet"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"walletLabel4"}
                    data-plasmic-override={overrides.walletLabel4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.walletLabel4)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame925"}
                      data-plasmic-override={overrides.frame925}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame925)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"icon4"}
                        data-plasmic-override={overrides.icon4}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.icon4)}
                      >
                        <IconsWalletLineIcon
                          className={classNames(projectcss.all, sty.svg__pyRvn)}
                          role={"img"}
                        />
                      </p.Stack>

                      <div
                        data-plasmic-name={"coinbaseWallet2"}
                        data-plasmic-override={overrides.coinbaseWallet2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.coinbaseWallet2
                        )}
                      >
                        {"Wallet Connect"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"termsOfService"}
                  data-plasmic-override={overrides.termsOfService}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.termsOfService)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"content"}
                    data-plasmic-override={overrides.content}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.content)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__psRk9
                      )}
                    >
                      {"Terms of service"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hts3Q
                      )}
                    >
                      {
                        "Please take a few minutes to read and understand Stacks\nTerms of Service. To continue, you’ll need to accept the terms of services by checking the boxes."
                      }
                    </div>
                  </p.Stack>

                  <div
                    data-plasmic-name={"qrCode"}
                    data-plasmic-override={overrides.qrCode}
                    className={classNames(projectcss.all, sty.qrCode)}
                  >
                    <div
                      data-plasmic-name={"cubes"}
                      data-plasmic-override={overrides.cubes}
                      className={classNames(projectcss.all, sty.cubes)}
                    >
                      <div
                        data-plasmic-name={"base"}
                        data-plasmic-override={overrides.base}
                        className={classNames(projectcss.all, sty.base)}
                      />

                      <div
                        data-plasmic-name={"colors"}
                        data-plasmic-override={overrides.colors}
                        className={classNames(projectcss.all, sty.colors)}
                      >
                        <div
                          data-plasmic-name={"_1"}
                          data-plasmic-override={overrides._1}
                          className={classNames(projectcss.all, sty._1)}
                        >
                          <div
                            data-plasmic-name={"_2"}
                            data-plasmic-override={overrides._2}
                            className={classNames(projectcss.all, sty._2)}
                          >
                            <div
                              data-plasmic-name={"colorsSwitcher"}
                              data-plasmic-override={overrides.colorsSwitcher}
                              className={classNames(
                                projectcss.all,
                                sty.colorsSwitcher
                              )}
                            >
                              <div
                                data-plasmic-name={"changeColorsHere"}
                                data-plasmic-override={
                                  overrides.changeColorsHere
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.changeColorsHere
                                )}
                              >
                                <div
                                  data-plasmic-name={"bg"}
                                  data-plasmic-override={overrides.bg}
                                  className={classNames(projectcss.all, sty.bg)}
                                />

                                <div
                                  data-plasmic-name={"_3"}
                                  data-plasmic-override={overrides._3}
                                  className={classNames(projectcss.all, sty._3)}
                                />

                                <div
                                  data-plasmic-name={"_4"}
                                  data-plasmic-override={overrides._4}
                                  className={classNames(projectcss.all, sty._4)}
                                />

                                <div
                                  data-plasmic-name={"_5"}
                                  data-plasmic-override={overrides._5}
                                  className={classNames(projectcss.all, sty._5)}
                                />
                              </div>
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"_6"}
                            data-plasmic-override={overrides._6}
                            className={classNames(projectcss.all, sty._6)}
                          >
                            <div
                              data-plasmic-name={"colorsSwitcher2"}
                              data-plasmic-override={overrides.colorsSwitcher2}
                              className={classNames(
                                projectcss.all,
                                sty.colorsSwitcher2
                              )}
                            >
                              <div
                                data-plasmic-name={"changeColorsHere2"}
                                data-plasmic-override={
                                  overrides.changeColorsHere2
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.changeColorsHere2
                                )}
                              >
                                <div
                                  data-plasmic-name={"bg2"}
                                  data-plasmic-override={overrides.bg2}
                                  className={classNames(
                                    projectcss.all,
                                    sty.bg2
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_7"}
                                  data-plasmic-override={overrides._7}
                                  className={classNames(projectcss.all, sty._7)}
                                />

                                <div
                                  data-plasmic-name={"_8"}
                                  data-plasmic-override={overrides._8}
                                  className={classNames(projectcss.all, sty._8)}
                                />

                                <div
                                  data-plasmic-name={"_9"}
                                  data-plasmic-override={overrides._9}
                                  className={classNames(projectcss.all, sty._9)}
                                />
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"_10"}
                          data-plasmic-override={overrides._10}
                          className={classNames(projectcss.all, sty._10)}
                        >
                          <div
                            data-plasmic-name={"_11"}
                            data-plasmic-override={overrides._11}
                            className={classNames(projectcss.all, sty._11)}
                          >
                            <div
                              data-plasmic-name={"colorsSwitcher3"}
                              data-plasmic-override={overrides.colorsSwitcher3}
                              className={classNames(
                                projectcss.all,
                                sty.colorsSwitcher3
                              )}
                            >
                              <div
                                data-plasmic-name={"changeColorsHere3"}
                                data-plasmic-override={
                                  overrides.changeColorsHere3
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.changeColorsHere3
                                )}
                              >
                                <div
                                  data-plasmic-name={"bg3"}
                                  data-plasmic-override={overrides.bg3}
                                  className={classNames(
                                    projectcss.all,
                                    sty.bg3
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_12"}
                                  data-plasmic-override={overrides._12}
                                  className={classNames(
                                    projectcss.all,
                                    sty._12
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_13"}
                                  data-plasmic-override={overrides._13}
                                  className={classNames(
                                    projectcss.all,
                                    sty._13
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_14"}
                                  data-plasmic-override={overrides._14}
                                  className={classNames(
                                    projectcss.all,
                                    sty._14
                                  )}
                                />
                              </div>
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"_15"}
                            data-plasmic-override={overrides._15}
                            className={classNames(projectcss.all, sty._15)}
                          >
                            <div
                              data-plasmic-name={"colorsSwitcher4"}
                              data-plasmic-override={overrides.colorsSwitcher4}
                              className={classNames(
                                projectcss.all,
                                sty.colorsSwitcher4
                              )}
                            >
                              <div
                                data-plasmic-name={"changeColorsHere4"}
                                data-plasmic-override={
                                  overrides.changeColorsHere4
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.changeColorsHere4
                                )}
                              >
                                <div
                                  data-plasmic-name={"bg4"}
                                  data-plasmic-override={overrides.bg4}
                                  className={classNames(
                                    projectcss.all,
                                    sty.bg4
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_16"}
                                  data-plasmic-override={overrides._16}
                                  className={classNames(
                                    projectcss.all,
                                    sty._16
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_17"}
                                  data-plasmic-override={overrides._17}
                                  className={classNames(
                                    projectcss.all,
                                    sty._17
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_18"}
                                  data-plasmic-override={overrides._18}
                                  className={classNames(
                                    projectcss.all,
                                    sty._18
                                  )}
                                />
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"_19"}
                          data-plasmic-override={overrides._19}
                          className={classNames(projectcss.all, sty._19)}
                        >
                          <div
                            data-plasmic-name={"_20"}
                            data-plasmic-override={overrides._20}
                            className={classNames(projectcss.all, sty._20)}
                          >
                            <div
                              data-plasmic-name={"colorsSwitcher5"}
                              data-plasmic-override={overrides.colorsSwitcher5}
                              className={classNames(
                                projectcss.all,
                                sty.colorsSwitcher5
                              )}
                            >
                              <div
                                data-plasmic-name={"changeColorsHere5"}
                                data-plasmic-override={
                                  overrides.changeColorsHere5
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.changeColorsHere5
                                )}
                              >
                                <div
                                  data-plasmic-name={"bg5"}
                                  data-plasmic-override={overrides.bg5}
                                  className={classNames(
                                    projectcss.all,
                                    sty.bg5
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_21"}
                                  data-plasmic-override={overrides._21}
                                  className={classNames(
                                    projectcss.all,
                                    sty._21
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_22"}
                                  data-plasmic-override={overrides._22}
                                  className={classNames(
                                    projectcss.all,
                                    sty._22
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_23"}
                                  data-plasmic-override={overrides._23}
                                  className={classNames(
                                    projectcss.all,
                                    sty._23
                                  )}
                                />
                              </div>
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"_24"}
                            data-plasmic-override={overrides._24}
                            className={classNames(projectcss.all, sty._24)}
                          >
                            <div
                              data-plasmic-name={"colorsSwitcher6"}
                              data-plasmic-override={overrides.colorsSwitcher6}
                              className={classNames(
                                projectcss.all,
                                sty.colorsSwitcher6
                              )}
                            >
                              <div
                                data-plasmic-name={"changeColorsHere6"}
                                data-plasmic-override={
                                  overrides.changeColorsHere6
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.changeColorsHere6
                                )}
                              >
                                <div
                                  data-plasmic-name={"bg6"}
                                  data-plasmic-override={overrides.bg6}
                                  className={classNames(
                                    projectcss.all,
                                    sty.bg6
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_25"}
                                  data-plasmic-override={overrides._25}
                                  className={classNames(
                                    projectcss.all,
                                    sty._25
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_26"}
                                  data-plasmic-override={overrides._26}
                                  className={classNames(
                                    projectcss.all,
                                    sty._26
                                  )}
                                />

                                <div
                                  data-plasmic-name={"_27"}
                                  data-plasmic-override={overrides._27}
                                  className={classNames(
                                    projectcss.all,
                                    sty._27
                                  )}
                                />
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div
                        data-plasmic-name={"specular"}
                        data-plasmic-override={overrides.specular}
                        className={classNames(projectcss.all, sty.specular)}
                      />

                      <div
                        data-plasmic-name={"specular2"}
                        data-plasmic-override={overrides.specular2}
                        className={classNames(projectcss.all, sty.specular2)}
                      />

                      <div
                        data-plasmic-name={"specular3"}
                        data-plasmic-override={overrides.specular3}
                        className={classNames(projectcss.all, sty.specular3)}
                      />
                    </div>
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame918"}
                    data-plasmic-override={overrides.frame918}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame918)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"checkbox"}
                      data-plasmic-override={overrides.checkbox}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.checkbox)}
                    >
                      <div
                        data-plasmic-name={"ratioButton"}
                        data-plasmic-override={overrides.ratioButton}
                        className={classNames(projectcss.all, sty.ratioButton)}
                      >
                        <IconsCheckLine2Icon
                          className={classNames(projectcss.all, sty.svg__bcEy)}
                          role={"img"}
                        />
                      </div>

                      <div
                        data-plasmic-name={"value"}
                        data-plasmic-override={overrides.value}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.value
                        )}
                      >
                        {"I am at least 13 year old"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"checkbox2"}
                      data-plasmic-override={overrides.checkbox2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.checkbox2)}
                    >
                      <div
                        data-plasmic-name={"ratioButton2"}
                        data-plasmic-override={overrides.ratioButton2}
                        className={classNames(projectcss.all, sty.ratioButton2)}
                      >
                        {false ? (
                          <IconsCheckLine2Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__thuG4
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </div>

                      <div
                        data-plasmic-name={"value2"}
                        data-plasmic-override={overrides.value2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.value2
                        )}
                      >
                        {"I agree Stack terms of service"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame926"}
                    data-plasmic-override={overrides.frame926}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame926)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button3"}
                      data-plasmic-override={overrides.button3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button3)}
                    >
                      <div
                        data-plasmic-name={"label3"}
                        data-plasmic-override={overrides.label3}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label3
                        )}
                      >
                        {"Cancel"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button4"}
                      data-plasmic-override={overrides.button4}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button4)}
                    >
                      <div
                        data-plasmic-name={"label4"}
                        data-plasmic-override={overrides.label4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label4
                        )}
                      >
                        {"Get started now"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <div
              data-plasmic-name={"footerDesktopLight"}
              data-plasmic-override={overrides.footerDesktopLight}
              className={classNames(projectcss.all, sty.footerDesktopLight)}
            >
              <div
                data-plasmic-name={"divider3"}
                data-plasmic-override={overrides.divider3}
                className={classNames(projectcss.all, sty.divider3)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"footer05DesktopLight"}
                data-plasmic-override={overrides.footer05DesktopLight}
                hasGap={true}
                className={classNames(projectcss.all, sty.footer05DesktopLight)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame789"}
                  data-plasmic-override={overrides.frame789}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame789)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame787"}
                    data-plasmic-override={overrides.frame787}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame787)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame774"}
                      data-plasmic-override={overrides.frame774}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame774)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"logo2"}
                        data-plasmic-override={overrides.logo2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.logo2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xpVnz
                          )}
                        >
                          {"Paperhouse"}
                        </div>
                      </p.Stack>

                      <div
                        data-plasmic-name={"letsMakeAGreatDesignTogerther"}
                        data-plasmic-override={
                          overrides.letsMakeAGreatDesignTogerther
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.letsMakeAGreatDesignTogerther
                        )}
                      >
                        {"An ecosystem for the new music industry."}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame783"}
                      data-plasmic-override={overrides.frame783}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame783)}
                    >
                      <div
                        data-plasmic-name={"crypter"}
                        data-plasmic-override={overrides.crypter}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.crypter
                        )}
                      >
                        {"From us"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame726"}
                        data-plasmic-override={overrides.frame726}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame726)}
                      >
                        <div
                          data-plasmic-name={"about"}
                          data-plasmic-override={overrides.about}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.about
                          )}
                        >
                          {"Discover"}
                        </div>

                        <div
                          data-plasmic-name={"projects"}
                          data-plasmic-override={overrides.projects}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.projects
                          )}
                        >
                          {"Connect wallet"}
                        </div>

                        <div
                          data-plasmic-name={"whatWeDo"}
                          data-plasmic-override={overrides.whatWeDo}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.whatWeDo
                          )}
                        >
                          {"Create item"}
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__atuBs
                            )}
                          >
                            {"Press"}
                          </div>
                        ) : null}
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dCcdv
                            )}
                          >
                            {"Jobs"}
                          </div>
                        ) : null}
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame784"}
                      data-plasmic-override={overrides.frame784}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame784)}
                    >
                      <div
                        data-plasmic-name={"info"}
                        data-plasmic-override={overrides.info}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.info
                        )}
                      >
                        {"Resources"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame727"}
                        data-plasmic-override={overrides.frame727}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame727)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6FVK
                          )}
                        >
                          {"Download"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ot1Yi
                          )}
                        >
                          {"Demos"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1OCit
                          )}
                        >
                          {"Support"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    {false ? (
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame786"}
                        data-plasmic-override={overrides.frame786}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame786)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vpZF
                          )}
                        >
                          {"Join Newsletter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame785"}
                          data-plasmic-override={overrides.frame785}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame785)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4HTW
                            )}
                          >
                            {
                              "Subscribe our newsletter to get more free design course and resource"
                            }
                          </div>

                          <div
                            data-plasmic-name={"singleInputField"}
                            data-plasmic-override={overrides.singleInputField}
                            className={classNames(
                              projectcss.all,
                              sty.singleInputField
                            )}
                          >
                            <div
                              data-plasmic-name={"enterYourEmail"}
                              data-plasmic-override={overrides.enterYourEmail}
                              className={classNames(
                                projectcss.all,
                                sty.enterYourEmail
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__nzRcD
                                )}
                              >
                                {"Enter your email"}
                              </div>
                            </div>

                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"smallCircleButton"}
                              data-plasmic-override={
                                overrides.smallCircleButton
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.smallCircleButton
                              )}
                            >
                              <IconsArrowRight2Line2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___7Pg4T
                                )}
                                role={"img"}
                              />
                            </p.Stack>
                          </div>
                        </p.Stack>
                      </p.Stack>
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"bottomBar"}
                    data-plasmic-override={overrides.bottomBar}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.bottomBar)}
                  >
                    <div
                      data-plasmic-name={"divider4"}
                      data-plasmic-override={overrides.divider4}
                      className={classNames(projectcss.all, sty.divider4)}
                    />

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"bottomBarContent"}
                      data-plasmic-override={overrides.bottomBarContent}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.bottomBarContent
                      )}
                    >
                      <div
                        data-plasmic-name={
                          "copyright2021Ui8LlcAllRightsReserved"
                        }
                        data-plasmic-override={
                          overrides.copyright2021Ui8LlcAllRightsReserved
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.copyright2021Ui8LlcAllRightsReserved
                        )}
                      >
                        {
                          "Copyright © 2021 Paperhouse LLC. All rights reserved."
                        }
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame788"}
                        data-plasmic-override={overrides.frame788}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame788)}
                      >
                        <div
                          data-plasmic-name={"weUseCookiesForBetterService"}
                          data-plasmic-override={
                            overrides.weUseCookiesForBetterService
                          }
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.weUseCookiesForBetterService
                          )}
                        >
                          {"We’re hiring!"}
                        </div>

                        <div
                          data-plasmic-name={"accept"}
                          data-plasmic-override={overrides.accept}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.accept
                          )}
                        >
                          {"Apply"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "connectWallet03DesktopLight",
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2",
    "connectWallet03DesktopLight2",
    "title",
    "frame924",
    "divider2",
    "frame923",
    "walletList",
    "walletLabel",
    "frame920",
    "icon",
    "walletLabel2",
    "frame921",
    "icon2",
    "walletLabel3",
    "frame922",
    "icon3",
    "coinbaseWallet",
    "walletLabel4",
    "frame925",
    "icon4",
    "coinbaseWallet2",
    "termsOfService",
    "content",
    "qrCode",
    "cubes",
    "base",
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27",
    "specular",
    "specular2",
    "specular3",
    "frame918",
    "checkbox",
    "ratioButton",
    "value",
    "checkbox2",
    "ratioButton2",
    "value2",
    "frame926",
    "button3",
    "label3",
    "button4",
    "label4",
    "footerDesktopLight",
    "divider3",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider4",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  connectWallet03DesktopLight: [
    "connectWallet03DesktopLight",
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2",
    "connectWallet03DesktopLight2",
    "title",
    "frame924",
    "divider2",
    "frame923",
    "walletList",
    "walletLabel",
    "frame920",
    "icon",
    "walletLabel2",
    "frame921",
    "icon2",
    "walletLabel3",
    "frame922",
    "icon3",
    "coinbaseWallet",
    "walletLabel4",
    "frame925",
    "icon4",
    "coinbaseWallet2",
    "termsOfService",
    "content",
    "qrCode",
    "cubes",
    "base",
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27",
    "specular",
    "specular2",
    "specular3",
    "frame918",
    "checkbox",
    "ratioButton",
    "value",
    "checkbox2",
    "ratioButton2",
    "value2",
    "frame926",
    "button3",
    "label3",
    "button4",
    "label4",
    "footerDesktopLight",
    "divider3",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider4",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  navDefaultDesktopLight: [
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2"
  ],

  navContent: [
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2"
  ],

  leftContent: ["leftContent", "logo", "divider"],
  logo: ["logo"],
  divider: ["divider"],
  actions: ["actions", "buttons", "button", "label", "button2", "label2"],
  buttons: ["buttons", "button", "label", "button2", "label2"],
  button: ["button", "label"],
  label: ["label"],
  button2: ["button2", "label2"],
  label2: ["label2"],
  connectWallet03DesktopLight2: [
    "connectWallet03DesktopLight2",
    "title",
    "frame924",
    "divider2",
    "frame923",
    "walletList",
    "walletLabel",
    "frame920",
    "icon",
    "walletLabel2",
    "frame921",
    "icon2",
    "walletLabel3",
    "frame922",
    "icon3",
    "coinbaseWallet",
    "walletLabel4",
    "frame925",
    "icon4",
    "coinbaseWallet2",
    "termsOfService",
    "content",
    "qrCode",
    "cubes",
    "base",
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27",
    "specular",
    "specular2",
    "specular3",
    "frame918",
    "checkbox",
    "ratioButton",
    "value",
    "checkbox2",
    "ratioButton2",
    "value2",
    "frame926",
    "button3",
    "label3",
    "button4",
    "label4"
  ],

  title: ["title", "frame924", "divider2"],
  frame924: ["frame924"],
  divider2: ["divider2"],
  frame923: [
    "frame923",
    "walletList",
    "walletLabel",
    "frame920",
    "icon",
    "walletLabel2",
    "frame921",
    "icon2",
    "walletLabel3",
    "frame922",
    "icon3",
    "coinbaseWallet",
    "walletLabel4",
    "frame925",
    "icon4",
    "coinbaseWallet2",
    "termsOfService",
    "content",
    "qrCode",
    "cubes",
    "base",
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27",
    "specular",
    "specular2",
    "specular3",
    "frame918",
    "checkbox",
    "ratioButton",
    "value",
    "checkbox2",
    "ratioButton2",
    "value2",
    "frame926",
    "button3",
    "label3",
    "button4",
    "label4"
  ],

  walletList: [
    "walletList",
    "walletLabel",
    "frame920",
    "icon",
    "walletLabel2",
    "frame921",
    "icon2",
    "walletLabel3",
    "frame922",
    "icon3",
    "coinbaseWallet",
    "walletLabel4",
    "frame925",
    "icon4",
    "coinbaseWallet2"
  ],

  walletLabel: ["walletLabel", "frame920", "icon"],
  frame920: ["frame920", "icon"],
  icon: ["icon"],
  walletLabel2: ["walletLabel2", "frame921", "icon2"],
  frame921: ["frame921", "icon2"],
  icon2: ["icon2"],
  walletLabel3: ["walletLabel3", "frame922", "icon3", "coinbaseWallet"],
  frame922: ["frame922", "icon3", "coinbaseWallet"],
  icon3: ["icon3"],
  coinbaseWallet: ["coinbaseWallet"],
  walletLabel4: ["walletLabel4", "frame925", "icon4", "coinbaseWallet2"],
  frame925: ["frame925", "icon4", "coinbaseWallet2"],
  icon4: ["icon4"],
  coinbaseWallet2: ["coinbaseWallet2"],
  termsOfService: [
    "termsOfService",
    "content",
    "qrCode",
    "cubes",
    "base",
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27",
    "specular",
    "specular2",
    "specular3",
    "frame918",
    "checkbox",
    "ratioButton",
    "value",
    "checkbox2",
    "ratioButton2",
    "value2",
    "frame926",
    "button3",
    "label3",
    "button4",
    "label4"
  ],

  content: ["content"],
  qrCode: [
    "qrCode",
    "cubes",
    "base",
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27",
    "specular",
    "specular2",
    "specular3"
  ],

  cubes: [
    "cubes",
    "base",
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27",
    "specular",
    "specular2",
    "specular3"
  ],

  base: ["base"],
  colors: [
    "colors",
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18",
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27"
  ],

  _1: [
    "_1",
    "_2",
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5",
    "_6",
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9"
  ],

  _2: ["_2", "colorsSwitcher", "changeColorsHere", "bg", "_3", "_4", "_5"],
  colorsSwitcher: [
    "colorsSwitcher",
    "changeColorsHere",
    "bg",
    "_3",
    "_4",
    "_5"
  ],

  changeColorsHere: ["changeColorsHere", "bg", "_3", "_4", "_5"],
  bg: ["bg"],
  _3: ["_3"],
  _4: ["_4"],
  _5: ["_5"],
  _6: ["_6", "colorsSwitcher2", "changeColorsHere2", "bg2", "_7", "_8", "_9"],
  colorsSwitcher2: [
    "colorsSwitcher2",
    "changeColorsHere2",
    "bg2",
    "_7",
    "_8",
    "_9"
  ],

  changeColorsHere2: ["changeColorsHere2", "bg2", "_7", "_8", "_9"],
  bg2: ["bg2"],
  _7: ["_7"],
  _8: ["_8"],
  _9: ["_9"],
  _10: [
    "_10",
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14",
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18"
  ],

  _11: [
    "_11",
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14"
  ],

  colorsSwitcher3: [
    "colorsSwitcher3",
    "changeColorsHere3",
    "bg3",
    "_12",
    "_13",
    "_14"
  ],

  changeColorsHere3: ["changeColorsHere3", "bg3", "_12", "_13", "_14"],
  bg3: ["bg3"],
  _12: ["_12"],
  _13: ["_13"],
  _14: ["_14"],
  _15: [
    "_15",
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18"
  ],

  colorsSwitcher4: [
    "colorsSwitcher4",
    "changeColorsHere4",
    "bg4",
    "_16",
    "_17",
    "_18"
  ],

  changeColorsHere4: ["changeColorsHere4", "bg4", "_16", "_17", "_18"],
  bg4: ["bg4"],
  _16: ["_16"],
  _17: ["_17"],
  _18: ["_18"],
  _19: [
    "_19",
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23",
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27"
  ],

  _20: [
    "_20",
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23"
  ],

  colorsSwitcher5: [
    "colorsSwitcher5",
    "changeColorsHere5",
    "bg5",
    "_21",
    "_22",
    "_23"
  ],

  changeColorsHere5: ["changeColorsHere5", "bg5", "_21", "_22", "_23"],
  bg5: ["bg5"],
  _21: ["_21"],
  _22: ["_22"],
  _23: ["_23"],
  _24: [
    "_24",
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27"
  ],

  colorsSwitcher6: [
    "colorsSwitcher6",
    "changeColorsHere6",
    "bg6",
    "_25",
    "_26",
    "_27"
  ],

  changeColorsHere6: ["changeColorsHere6", "bg6", "_25", "_26", "_27"],
  bg6: ["bg6"],
  _25: ["_25"],
  _26: ["_26"],
  _27: ["_27"],
  specular: ["specular"],
  specular2: ["specular2"],
  specular3: ["specular3"],
  frame918: [
    "frame918",
    "checkbox",
    "ratioButton",
    "value",
    "checkbox2",
    "ratioButton2",
    "value2"
  ],

  checkbox: ["checkbox", "ratioButton", "value"],
  ratioButton: ["ratioButton"],
  value: ["value"],
  checkbox2: ["checkbox2", "ratioButton2", "value2"],
  ratioButton2: ["ratioButton2"],
  value2: ["value2"],
  frame926: ["frame926", "button3", "label3", "button4", "label4"],
  button3: ["button3", "label3"],
  label3: ["label3"],
  button4: ["button4", "label4"],
  label4: ["label4"],
  footerDesktopLight: [
    "footerDesktopLight",
    "divider3",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider4",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider3: ["divider3"],
  footer05DesktopLight: [
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider4",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame789: [
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider4",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame787: [
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame774: ["frame774", "logo2", "letsMakeAGreatDesignTogerther"],
  logo2: ["logo2"],
  letsMakeAGreatDesignTogerther: ["letsMakeAGreatDesignTogerther"],
  frame783: [
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo"
  ],

  crypter: ["crypter"],
  frame726: ["frame726", "about", "projects", "whatWeDo"],
  about: ["about"],
  projects: ["projects"],
  whatWeDo: ["whatWeDo"],
  frame784: ["frame784", "info", "frame727"],
  info: ["info"],
  frame727: ["frame727"],
  frame786: [
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame785: [
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  singleInputField: ["singleInputField", "enterYourEmail", "smallCircleButton"],
  enterYourEmail: ["enterYourEmail"],
  smallCircleButton: ["smallCircleButton"],
  bottomBar: [
    "bottomBar",
    "divider4",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider4: ["divider4"],
  bottomBarContent: [
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  copyright2021Ui8LlcAllRightsReserved: [
    "copyright2021Ui8LlcAllRightsReserved"
  ],

  frame788: ["frame788", "weUseCookiesForBetterService", "accept"],
  weUseCookiesForBetterService: ["weUseCookiesForBetterService"],
  accept: ["accept"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicConnectWallet__ArgProps,
      internalVariantPropNames: PlasmicConnectWallet__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicConnectWallet__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicConnectWallet";
  } else {
    func.displayName = `PlasmicConnectWallet.${nodeName}`;
  }
  return func;
}

export const PlasmicConnectWallet = Object.assign(
  // Top-level PlasmicConnectWallet renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    connectWallet03DesktopLight: makeNodeComponent(
      "connectWallet03DesktopLight"
    ),

    navDefaultDesktopLight: makeNodeComponent("navDefaultDesktopLight"),
    navContent: makeNodeComponent("navContent"),
    leftContent: makeNodeComponent("leftContent"),
    logo: makeNodeComponent("logo"),
    divider: makeNodeComponent("divider"),
    actions: makeNodeComponent("actions"),
    buttons: makeNodeComponent("buttons"),
    button: makeNodeComponent("button"),
    label: makeNodeComponent("label"),
    button2: makeNodeComponent("button2"),
    label2: makeNodeComponent("label2"),
    connectWallet03DesktopLight2: makeNodeComponent(
      "connectWallet03DesktopLight2"
    ),

    title: makeNodeComponent("title"),
    frame924: makeNodeComponent("frame924"),
    divider2: makeNodeComponent("divider2"),
    frame923: makeNodeComponent("frame923"),
    walletList: makeNodeComponent("walletList"),
    walletLabel: makeNodeComponent("walletLabel"),
    frame920: makeNodeComponent("frame920"),
    icon: makeNodeComponent("icon"),
    walletLabel2: makeNodeComponent("walletLabel2"),
    frame921: makeNodeComponent("frame921"),
    icon2: makeNodeComponent("icon2"),
    walletLabel3: makeNodeComponent("walletLabel3"),
    frame922: makeNodeComponent("frame922"),
    icon3: makeNodeComponent("icon3"),
    coinbaseWallet: makeNodeComponent("coinbaseWallet"),
    walletLabel4: makeNodeComponent("walletLabel4"),
    frame925: makeNodeComponent("frame925"),
    icon4: makeNodeComponent("icon4"),
    coinbaseWallet2: makeNodeComponent("coinbaseWallet2"),
    termsOfService: makeNodeComponent("termsOfService"),
    content: makeNodeComponent("content"),
    qrCode: makeNodeComponent("qrCode"),
    cubes: makeNodeComponent("cubes"),
    base: makeNodeComponent("base"),
    colors: makeNodeComponent("colors"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    colorsSwitcher: makeNodeComponent("colorsSwitcher"),
    changeColorsHere: makeNodeComponent("changeColorsHere"),
    bg: makeNodeComponent("bg"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    _5: makeNodeComponent("_5"),
    _6: makeNodeComponent("_6"),
    colorsSwitcher2: makeNodeComponent("colorsSwitcher2"),
    changeColorsHere2: makeNodeComponent("changeColorsHere2"),
    bg2: makeNodeComponent("bg2"),
    _7: makeNodeComponent("_7"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    colorsSwitcher3: makeNodeComponent("colorsSwitcher3"),
    changeColorsHere3: makeNodeComponent("changeColorsHere3"),
    bg3: makeNodeComponent("bg3"),
    _12: makeNodeComponent("_12"),
    _13: makeNodeComponent("_13"),
    _14: makeNodeComponent("_14"),
    _15: makeNodeComponent("_15"),
    colorsSwitcher4: makeNodeComponent("colorsSwitcher4"),
    changeColorsHere4: makeNodeComponent("changeColorsHere4"),
    bg4: makeNodeComponent("bg4"),
    _16: makeNodeComponent("_16"),
    _17: makeNodeComponent("_17"),
    _18: makeNodeComponent("_18"),
    _19: makeNodeComponent("_19"),
    _20: makeNodeComponent("_20"),
    colorsSwitcher5: makeNodeComponent("colorsSwitcher5"),
    changeColorsHere5: makeNodeComponent("changeColorsHere5"),
    bg5: makeNodeComponent("bg5"),
    _21: makeNodeComponent("_21"),
    _22: makeNodeComponent("_22"),
    _23: makeNodeComponent("_23"),
    _24: makeNodeComponent("_24"),
    colorsSwitcher6: makeNodeComponent("colorsSwitcher6"),
    changeColorsHere6: makeNodeComponent("changeColorsHere6"),
    bg6: makeNodeComponent("bg6"),
    _25: makeNodeComponent("_25"),
    _26: makeNodeComponent("_26"),
    _27: makeNodeComponent("_27"),
    specular: makeNodeComponent("specular"),
    specular2: makeNodeComponent("specular2"),
    specular3: makeNodeComponent("specular3"),
    frame918: makeNodeComponent("frame918"),
    checkbox: makeNodeComponent("checkbox"),
    ratioButton: makeNodeComponent("ratioButton"),
    value: makeNodeComponent("value"),
    checkbox2: makeNodeComponent("checkbox2"),
    ratioButton2: makeNodeComponent("ratioButton2"),
    value2: makeNodeComponent("value2"),
    frame926: makeNodeComponent("frame926"),
    button3: makeNodeComponent("button3"),
    label3: makeNodeComponent("label3"),
    button4: makeNodeComponent("button4"),
    label4: makeNodeComponent("label4"),
    footerDesktopLight: makeNodeComponent("footerDesktopLight"),
    divider3: makeNodeComponent("divider3"),
    footer05DesktopLight: makeNodeComponent("footer05DesktopLight"),
    frame789: makeNodeComponent("frame789"),
    frame787: makeNodeComponent("frame787"),
    frame774: makeNodeComponent("frame774"),
    logo2: makeNodeComponent("logo2"),
    letsMakeAGreatDesignTogerther: makeNodeComponent(
      "letsMakeAGreatDesignTogerther"
    ),

    frame783: makeNodeComponent("frame783"),
    crypter: makeNodeComponent("crypter"),
    frame726: makeNodeComponent("frame726"),
    about: makeNodeComponent("about"),
    projects: makeNodeComponent("projects"),
    whatWeDo: makeNodeComponent("whatWeDo"),
    frame784: makeNodeComponent("frame784"),
    info: makeNodeComponent("info"),
    frame727: makeNodeComponent("frame727"),
    frame786: makeNodeComponent("frame786"),
    frame785: makeNodeComponent("frame785"),
    singleInputField: makeNodeComponent("singleInputField"),
    enterYourEmail: makeNodeComponent("enterYourEmail"),
    smallCircleButton: makeNodeComponent("smallCircleButton"),
    bottomBar: makeNodeComponent("bottomBar"),
    divider4: makeNodeComponent("divider4"),
    bottomBarContent: makeNodeComponent("bottomBarContent"),
    copyright2021Ui8LlcAllRightsReserved: makeNodeComponent(
      "copyright2021Ui8LlcAllRightsReserved"
    ),

    frame788: makeNodeComponent("frame788"),
    weUseCookiesForBetterService: makeNodeComponent(
      "weUseCookiesForBetterService"
    ),

    accept: makeNodeComponent("accept"),
    // Metadata about props expected for PlasmicConnectWallet
    internalVariantProps: PlasmicConnectWallet__VariantProps,
    internalArgProps: PlasmicConnectWallet__ArgProps
  }
);

export default PlasmicConnectWallet;
/* prettier-ignore-end */
