// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 73KhD343S1ps4YNpRNR2Mg
// Component: Io5LOrZjHh
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_paper_house.module.css"; // plasmic-import: 73KhD343S1ps4YNpRNR2Mg/projectcss
import sty from "./PlasmicPlaceABid.module.css"; // plasmic-import: Io5LOrZjHh/css
import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: oHxAsKWJqRM/icon
import IconsCloseLineIcon from "./icons/PlasmicIcon__IconsCloseLine"; // plasmic-import: ye63VZdaNB6/icon
import IconsHeartFilledIcon from "./icons/PlasmicIcon__IconsHeartFilled"; // plasmic-import: 6dOrqJgVsot/icon
import IconsArrowRight2Line2Icon from "./icons/PlasmicIcon__IconsArrowRight2Line2"; // plasmic-import: ojVcl76mJo1/icon
import IconsWalletLineIcon from "./icons/PlasmicIcon__IconsWalletLine"; // plasmic-import: AsHTec35ur9/icon

export const PlasmicPlaceABid__VariantProps = new Array();

export const PlasmicPlaceABid__ArgProps = new Array();

function PlasmicPlaceABid__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"placeABidDesktopTabletLight"}
            data-plasmic-override={overrides.placeABidDesktopTabletLight}
            className={classNames(
              projectcss.all,
              sty.placeABidDesktopTabletLight
            )}
          >
            <div
              data-plasmic-name={"item01DesktopLight"}
              data-plasmic-override={overrides.item01DesktopLight}
              className={classNames(projectcss.all, sty.item01DesktopLight)}
            >
              <div
                data-plasmic-name={"navDefaultDesktopLight"}
                data-plasmic-override={overrides.navDefaultDesktopLight}
                className={classNames(
                  projectcss.all,
                  sty.navDefaultDesktopLight
                )}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"navContent"}
                  data-plasmic-override={overrides.navContent}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navContent)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"leftContent"}
                    data-plasmic-override={overrides.leftContent}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.leftContent)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"logo"}
                      data-plasmic-override={overrides.logo}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.logo)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b92F
                        )}
                      >
                        {"Paperhouse"}
                      </div>
                    </p.Stack>

                    <div
                      data-plasmic-name={"divider"}
                      data-plasmic-override={overrides.divider}
                      className={classNames(projectcss.all, sty.divider)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vVlyj
                      )}
                    >
                      {"Search"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gPtcp
                      )}
                    >
                      {"How it works"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"actions"}
                    data-plasmic-override={overrides.actions}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.actions)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"buttons"}
                      data-plasmic-override={overrides.buttons}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.buttons)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.button)}
                      >
                        <div
                          data-plasmic-name={"label"}
                          data-plasmic-override={overrides.label}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label
                          )}
                        >
                          {"Create"}
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"button2"}
                        data-plasmic-override={overrides.button2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.button2)}
                      >
                        <div
                          data-plasmic-name={"label2"}
                          data-plasmic-override={overrides.label2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label2
                          )}
                        >
                          {"Open collection"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"itemDesktopLight"}
                data-plasmic-override={overrides.itemDesktopLight}
                hasGap={true}
                className={classNames(projectcss.all, sty.itemDesktopLight)}
              >
                <div
                  data-plasmic-name={"group34"}
                  data-plasmic-override={overrides.group34}
                  className={classNames(projectcss.all, sty.group34)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"itemWrap"}
                    data-plasmic-override={overrides.itemWrap}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.itemWrap)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame1105"}
                      data-plasmic-override={overrides.frame1105}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame1105)}
                    >
                      <div
                        data-plasmic-name={"itemCard"}
                        data-plasmic-override={overrides.itemCard}
                        className={classNames(projectcss.all, sty.itemCard)}
                      >
                        <div
                          data-plasmic-name={"productImg"}
                          data-plasmic-override={overrides.productImg}
                          className={classNames(projectcss.all, sty.productImg)}
                        >
                          <div
                            data-plasmic-name={"media10"}
                            data-plasmic-override={overrides.media10}
                            className={classNames(projectcss.all, sty.media10)}
                          >
                            <div
                              data-plasmic-name={"imgLibimg114"}
                              data-plasmic-override={overrides.imgLibimg114}
                              className={classNames(
                                projectcss.all,
                                sty.imgLibimg114
                              )}
                            >
                              <div
                                data-plasmic-name={"fuuJCLoSgOrJu6SUnsplash1"}
                                data-plasmic-override={
                                  overrides.fuuJCLoSgOrJu6SUnsplash1
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.fuuJcLoSgOrJu6SUnsplash1
                                )}
                              />

                              <div
                                data-plasmic-name={
                                  "michaelDziedzicLFxVNhopfsUnsplash1"
                                }
                                data-plasmic-override={
                                  overrides.michaelDziedzicLFxVNhopfsUnsplash1
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.michaelDziedzicLFxVNhopfsUnsplash1
                                )}
                              />
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"idkAlbumClean111"}
                            data-plasmic-override={overrides.idkAlbumClean111}
                            className={classNames(
                              projectcss.all,
                              sty.idkAlbumClean111
                            )}
                          />
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"itemInfo"}
                          data-plasmic-override={overrides.itemInfo}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.itemInfo)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"titlePrice"}
                            data-plasmic-override={overrides.titlePrice}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.titlePrice
                            )}
                          >
                            <div
                              data-plasmic-name={"usee4Urself"}
                              data-plasmic-override={overrides.usee4Urself}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.usee4Urself
                              )}
                            >
                              {"Amputechture"}
                            </div>

                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"label3"}
                              data-plasmic-override={overrides.label3}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.label3)}
                            >
                              <div
                                data-plasmic-name={"popular"}
                                data-plasmic-override={overrides.popular}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.popular
                                )}
                              >
                                {"243 SOL"}
                              </div>
                            </p.Stack>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"titlePrice2"}
                            data-plasmic-override={overrides.titlePrice2}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.titlePrice2
                            )}
                          >
                            <div
                              data-plasmic-name={"idk"}
                              data-plasmic-override={overrides.idk}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.idk
                              )}
                            >
                              {"The Mars Volta"}
                            </div>

                            <div
                              data-plasmic-name={"frame1092"}
                              data-plasmic-override={overrides.frame1092}
                              className={classNames(
                                projectcss.all,
                                sty.frame1092
                              )}
                            >
                              <div
                                data-plasmic-name={"release"}
                                data-plasmic-override={overrides.release}
                                className={classNames(
                                  projectcss.all,
                                  sty.release
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__ldpPz
                                  )}
                                >
                                  {"RELEASE"}
                                </div>
                              </div>

                              <p.Stack
                                as={"div"}
                                data-plasmic-name={"highestBid"}
                                data-plasmic-override={overrides.highestBid}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.highestBid
                                )}
                              />
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame971"}
                        data-plasmic-override={overrides.frame971}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame971)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame970"}
                          data-plasmic-override={overrides.frame970}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame970)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame1104"}
                            data-plasmic-override={overrides.frame1104}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.frame1104
                            )}
                          >
                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"productTitlePrice"}
                              data-plasmic-override={
                                overrides.productTitlePrice
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.productTitlePrice
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__w7JHb
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__aeVOy
                                  )}
                                >
                                  {"Amputechture"}
                                </div>

                                <p.Stack
                                  as={"div"}
                                  data-plasmic-name={"frame1103"}
                                  data-plasmic-override={overrides.frame1103}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame1103
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__yawT6
                                    )}
                                  >
                                    {"The Mars Volta"}
                                  </div>

                                  <p.Stack
                                    as={FrameIcon}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___3LkCh
                                    )}
                                    role={"img"}
                                  />
                                </p.Stack>

                                <p.Stack
                                  as={"div"}
                                  data-plasmic-name={"frame952"}
                                  data-plasmic-override={overrides.frame952}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame952
                                  )}
                                >
                                  <p.Stack
                                    as={"div"}
                                    data-plasmic-name={"price"}
                                    data-plasmic-override={overrides.price}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.price
                                    )}
                                  >
                                    <div
                                      data-plasmic-name={"popular2"}
                                      data-plasmic-override={overrides.popular2}
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.popular2
                                      )}
                                    >
                                      {"STANDARD"}
                                    </div>
                                  </p.Stack>
                                </p.Stack>
                              </p.Stack>
                            </p.Stack>

                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"frame963"}
                              data-plasmic-override={overrides.frame963}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.frame963
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__iq9Cq
                                )}
                              >
                                {
                                  "Holding this album will give you access to bonus surprises, directly from the artist. This is where they will tell you about it."
                                }
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___9VyqP
                                )}
                              >
                                {"There are 10 copies remaining."}
                              </div>
                            </p.Stack>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"fixedBox"}
                            data-plasmic-override={overrides.fixedBox}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.fixedBox)}
                          >
                            {false ? (
                              <p.Stack
                                as={"div"}
                                data-plasmic-name={"frame1087"}
                                data-plasmic-override={overrides.frame1087}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame1087
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__dRAc3
                                  )}
                                >
                                  {false ? (
                                    <p.Stack
                                      as={"div"}
                                      data-plasmic-name={"frame960"}
                                      data-plasmic-override={overrides.frame960}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.frame960
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          sty.freeBox__xhU8U
                                        )}
                                      >
                                        <div
                                          data-plasmic-name={"frame959"}
                                          data-plasmic-override={
                                            overrides.frame959
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.frame959
                                          )}
                                        >
                                          <p.Stack
                                            as={"div"}
                                            data-plasmic-name={"frame956"}
                                            data-plasmic-override={
                                              overrides.frame956
                                            }
                                            hasGap={true}
                                            className={classNames(
                                              projectcss.all,
                                              sty.frame956
                                            )}
                                          >
                                            <div
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.text__syh3U
                                              )}
                                            >
                                              {"Highest bid by"}
                                            </div>

                                            <p.Stack
                                              as={"div"}
                                              data-plasmic-name={"frame955"}
                                              data-plasmic-override={
                                                overrides.frame955
                                              }
                                              hasGap={true}
                                              className={classNames(
                                                projectcss.all,
                                                sty.frame955
                                              )}
                                            >
                                              <div
                                                className={classNames(
                                                  projectcss.all,
                                                  projectcss.__wab_text,
                                                  sty.text__lwgWt
                                                )}
                                              >
                                                {"Kohaku"}
                                              </div>

                                              <div
                                                className={classNames(
                                                  projectcss.all,
                                                  projectcss.__wab_text,
                                                  sty.text__x012E
                                                )}
                                              >
                                                {"Tora"}
                                              </div>
                                            </p.Stack>
                                          </p.Stack>

                                          <p.Stack
                                            as={"div"}
                                            data-plasmic-name={"frame954"}
                                            data-plasmic-override={
                                              overrides.frame954
                                            }
                                            hasGap={true}
                                            className={classNames(
                                              projectcss.all,
                                              sty.frame954
                                            )}
                                          >
                                            <div
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.text__mlBMt
                                              )}
                                            >
                                              {"1.46 ETH"}
                                            </div>

                                            <div
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.text__pu8H4
                                              )}
                                            >
                                              {"$2,764.89"}
                                            </div>
                                          </p.Stack>
                                        </div>
                                      </div>

                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          sty.freeBox__nkNrR
                                        )}
                                      >
                                        <div
                                          data-plasmic-name={"avatar01"}
                                          data-plasmic-override={
                                            overrides.avatar01
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.avatar01
                                          )}
                                        >
                                          <div
                                            data-plasmic-name={
                                              "austinWadeX6Uj51N5Ce8Unsplash1"
                                            }
                                            data-plasmic-override={
                                              overrides.austinWadeX6Uj51N5Ce8Unsplash1
                                            }
                                            className={classNames(
                                              projectcss.all,
                                              sty.austinWadeX6Uj51N5Ce8Unsplash1
                                            )}
                                          />
                                        </div>
                                      </div>
                                    </p.Stack>
                                  ) : null}
                                </div>
                              </p.Stack>
                            ) : null}

                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"frame958"}
                              data-plasmic-override={overrides.frame958}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.frame958
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                data-plasmic-name={"button3"}
                                data-plasmic-override={overrides.button3}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.button3
                                )}
                              >
                                <div
                                  data-plasmic-name={"label4"}
                                  data-plasmic-override={overrides.label4}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.label4
                                  )}
                                >
                                  {"Purchase now"}
                                </div>
                              </p.Stack>

                              {false ? (
                                <p.Stack
                                  as={"div"}
                                  data-plasmic-name={"button4"}
                                  data-plasmic-override={overrides.button4}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.button4
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"label5"}
                                    data-plasmic-override={overrides.label5}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.label5
                                    )}
                                  >
                                    {"Place a bid"}
                                  </div>
                                </p.Stack>
                              ) : null}
                            </p.Stack>

                            {false ? (
                              <p.Stack
                                as={"div"}
                                data-plasmic-name={"frame957"}
                                data-plasmic-override={overrides.frame957}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame957
                                )}
                              >
                                {false ? (
                                  <div
                                    data-plasmic-name={"serviceFee"}
                                    data-plasmic-override={overrides.serviceFee}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.serviceFee
                                    )}
                                  >
                                    {"Price:"}
                                  </div>
                                ) : null}

                                <div
                                  data-plasmic-name={"_15"}
                                  data-plasmic-override={overrides._15}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty._15
                                  )}
                                >
                                  {"243 SOL"}
                                </div>

                                <div
                                  data-plasmic-name={"_2563Eth"}
                                  data-plasmic-override={overrides._2563Eth}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty._2563Eth
                                  )}
                                >
                                  {"$24.62 USD"}
                                </div>

                                {false ? (
                                  <div
                                    data-plasmic-name={"_454062"}
                                    data-plasmic-override={overrides._454062}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty._454062
                                    )}
                                  >
                                    {"Service fees incl."}
                                  </div>
                                ) : null}
                              </p.Stack>
                            ) : null}
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"icons"}
                      data-plasmic-override={overrides.icons}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.icons)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"share"}
                        data-plasmic-override={overrides.share}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.share)}
                      >
                        <IconsCloseLineIcon
                          className={classNames(projectcss.all, sty.svg__l3FNk)}
                          role={"img"}
                        />
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"love"}
                        data-plasmic-override={overrides.love}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.love)}
                      >
                        <IconsHeartFilledIcon
                          className={classNames(projectcss.all, sty.svg__qi8Ky)}
                          role={"img"}
                        />
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"footerDesktopLight"}
                data-plasmic-override={overrides.footerDesktopLight}
                className={classNames(projectcss.all, sty.footerDesktopLight)}
              >
                <div
                  data-plasmic-name={"divider2"}
                  data-plasmic-override={overrides.divider2}
                  className={classNames(projectcss.all, sty.divider2)}
                />

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"footer05DesktopLight"}
                  data-plasmic-override={overrides.footer05DesktopLight}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    sty.footer05DesktopLight
                  )}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame789"}
                    data-plasmic-override={overrides.frame789}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame789)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame787"}
                      data-plasmic-override={overrides.frame787}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame787)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame774"}
                        data-plasmic-override={overrides.frame774}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame774)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"logo2"}
                          data-plasmic-override={overrides.logo2}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.logo2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wfZLc
                            )}
                          >
                            {"Paperhouse"}
                          </div>
                        </p.Stack>

                        <div
                          data-plasmic-name={"letsMakeAGreatDesignTogerther"}
                          data-plasmic-override={
                            overrides.letsMakeAGreatDesignTogerther
                          }
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.letsMakeAGreatDesignTogerther
                          )}
                        >
                          {"An ecosystem for the new music industry."}
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame783"}
                        data-plasmic-override={overrides.frame783}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame783)}
                      >
                        <div
                          data-plasmic-name={"crypter"}
                          data-plasmic-override={overrides.crypter}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.crypter
                          )}
                        >
                          {"From us"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame726"}
                          data-plasmic-override={overrides.frame726}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame726)}
                        >
                          <div
                            data-plasmic-name={"about"}
                            data-plasmic-override={overrides.about}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.about
                            )}
                          >
                            {"Discover"}
                          </div>

                          <div
                            data-plasmic-name={"projects"}
                            data-plasmic-override={overrides.projects}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.projects
                            )}
                          >
                            {"Connect wallet"}
                          </div>

                          <div
                            data-plasmic-name={"whatWeDo"}
                            data-plasmic-override={overrides.whatWeDo}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.whatWeDo
                            )}
                          >
                            {"Create item"}
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wbm56
                              )}
                            >
                              {"Press"}
                            </div>
                          ) : null}
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2DJ68
                              )}
                            >
                              {"Jobs"}
                            </div>
                          ) : null}
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame784"}
                        data-plasmic-override={overrides.frame784}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame784)}
                      >
                        <div
                          data-plasmic-name={"info"}
                          data-plasmic-override={overrides.info}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.info
                          )}
                        >
                          {"Resources"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame727"}
                          data-plasmic-override={overrides.frame727}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame727)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lb1DC
                            )}
                          >
                            {"Download"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___47Fse
                            )}
                          >
                            {"Demos"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3My8H
                            )}
                          >
                            {"Support"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      {false ? (
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame786"}
                          data-plasmic-override={overrides.frame786}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame786)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kkKeg
                            )}
                          >
                            {"Join Newsletter"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame785"}
                            data-plasmic-override={overrides.frame785}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame785)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__f13Jr
                              )}
                            >
                              {
                                "Subscribe our newsletter to get more free design course and resource"
                              }
                            </div>

                            <div
                              data-plasmic-name={"singleInputField"}
                              data-plasmic-override={overrides.singleInputField}
                              className={classNames(
                                projectcss.all,
                                sty.singleInputField
                              )}
                            >
                              <div
                                data-plasmic-name={"enterYourEmail"}
                                data-plasmic-override={overrides.enterYourEmail}
                                className={classNames(
                                  projectcss.all,
                                  sty.enterYourEmail
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__twEdW
                                  )}
                                >
                                  {"Enter your email"}
                                </div>
                              </div>

                              <p.Stack
                                as={"div"}
                                data-plasmic-name={"smallCircleButton"}
                                data-plasmic-override={
                                  overrides.smallCircleButton
                                }
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.smallCircleButton
                                )}
                              >
                                <IconsArrowRight2Line2Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__jrvId
                                  )}
                                  role={"img"}
                                />
                              </p.Stack>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"bottomBar"}
                      data-plasmic-override={overrides.bottomBar}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.bottomBar)}
                    >
                      <div
                        data-plasmic-name={"divider3"}
                        data-plasmic-override={overrides.divider3}
                        className={classNames(projectcss.all, sty.divider3)}
                      />

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"bottomBarContent"}
                        data-plasmic-override={overrides.bottomBarContent}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.bottomBarContent
                        )}
                      >
                        <div
                          data-plasmic-name={
                            "copyright2021Ui8LlcAllRightsReserved"
                          }
                          data-plasmic-override={
                            overrides.copyright2021Ui8LlcAllRightsReserved
                          }
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.copyright2021Ui8LlcAllRightsReserved
                          )}
                        >
                          {
                            "Copyright © 2021 Paperhouse LLC. All rights reserved."
                          }
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame788"}
                          data-plasmic-override={overrides.frame788}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame788)}
                        >
                          <div
                            data-plasmic-name={"weUseCookiesForBetterService"}
                            data-plasmic-override={
                              overrides.weUseCookiesForBetterService
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.weUseCookiesForBetterService
                            )}
                          >
                            {"We’re hiring!"}
                          </div>

                          <div
                            data-plasmic-name={"accept"}
                            data-plasmic-override={overrides.accept}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.accept
                            )}
                          >
                            {"Apply"}
                          </div>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </div>
            </div>

            <div
              data-plasmic-name={"overlay"}
              data-plasmic-override={overrides.overlay}
              className={classNames(projectcss.all, sty.overlay)}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"modalPlaceABidPlaceABid01Light"}
              data-plasmic-override={overrides.modalPlaceABidPlaceABid01Light}
              hasGap={true}
              className={classNames(
                projectcss.all,
                sty.modalPlaceABidPlaceABid01Light
              )}
            >
              <div
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames(projectcss.all, sty.title)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wo4Ak
                  )}
                >
                  {"Checkout"}
                </div>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"share2"}
                  data-plasmic-override={overrides.share2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.share2)}
                >
                  <IconsCloseLineIcon
                    className={classNames(projectcss.all, sty.svg___3UiQy)}
                    role={"img"}
                  />
                </p.Stack>
              </div>

              <div
                data-plasmic-name={"frame1064"}
                data-plasmic-override={overrides.frame1064}
                className={classNames(projectcss.all, sty.frame1064)}
              >
                <IconsWalletLineIcon
                  className={classNames(projectcss.all, sty.svg___2LWuG)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fnKzu
                )}
              >
                {
                  "You need to connect your wallet first to sign messages and send transaction to Ethereum network"
                }
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"buttons2"}
                data-plasmic-override={overrides.buttons2}
                hasGap={true}
                className={classNames(projectcss.all, sty.buttons2)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"button5"}
                  data-plasmic-override={overrides.button5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.button5)}
                >
                  <div
                    data-plasmic-name={"label6"}
                    data-plasmic-override={overrides.label6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label6
                    )}
                  >
                    {"Connect wallet"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"button6"}
                  data-plasmic-override={overrides.button6}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.button6)}
                >
                  <div
                    data-plasmic-name={"label7"}
                    data-plasmic-override={overrides.label7}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label7
                    )}
                  >
                    {"Cancel"}
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "placeABidDesktopTabletLight",
    "item01DesktopLight",
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2",
    "itemDesktopLight",
    "group34",
    "itemWrap",
    "frame1105",
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid",
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062",
    "icons",
    "share",
    "love",
    "footerDesktopLight",
    "divider2",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider3",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept",
    "overlay",
    "modalPlaceABidPlaceABid01Light",
    "title",
    "share2",
    "frame1064",
    "buttons2",
    "button5",
    "label6",
    "button6",
    "label7"
  ],

  placeABidDesktopTabletLight: [
    "placeABidDesktopTabletLight",
    "item01DesktopLight",
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2",
    "itemDesktopLight",
    "group34",
    "itemWrap",
    "frame1105",
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid",
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062",
    "icons",
    "share",
    "love",
    "footerDesktopLight",
    "divider2",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider3",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept",
    "overlay",
    "modalPlaceABidPlaceABid01Light",
    "title",
    "share2",
    "frame1064",
    "buttons2",
    "button5",
    "label6",
    "button6",
    "label7"
  ],

  item01DesktopLight: [
    "item01DesktopLight",
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2",
    "itemDesktopLight",
    "group34",
    "itemWrap",
    "frame1105",
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid",
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062",
    "icons",
    "share",
    "love",
    "footerDesktopLight",
    "divider2",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider3",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  navDefaultDesktopLight: [
    "navDefaultDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2"
  ],

  navContent: [
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "button2",
    "label2"
  ],

  leftContent: ["leftContent", "logo", "divider"],
  logo: ["logo"],
  divider: ["divider"],
  actions: ["actions", "buttons", "button", "label", "button2", "label2"],
  buttons: ["buttons", "button", "label", "button2", "label2"],
  button: ["button", "label"],
  label: ["label"],
  button2: ["button2", "label2"],
  label2: ["label2"],
  itemDesktopLight: [
    "itemDesktopLight",
    "group34",
    "itemWrap",
    "frame1105",
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid",
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062",
    "icons",
    "share",
    "love"
  ],

  group34: [
    "group34",
    "itemWrap",
    "frame1105",
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid",
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062",
    "icons",
    "share",
    "love"
  ],

  itemWrap: [
    "itemWrap",
    "frame1105",
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid",
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062",
    "icons",
    "share",
    "love"
  ],

  frame1105: [
    "frame1105",
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid",
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062"
  ],

  itemCard: [
    "itemCard",
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111",
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid"
  ],

  productImg: [
    "productImg",
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1",
    "idkAlbumClean111"
  ],

  media10: [
    "media10",
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1"
  ],

  imgLibimg114: [
    "imgLibimg114",
    "fuuJCLoSgOrJu6SUnsplash1",
    "michaelDziedzicLFxVNhopfsUnsplash1"
  ],

  fuuJCLoSgOrJu6SUnsplash1: ["fuuJCLoSgOrJu6SUnsplash1"],
  michaelDziedzicLFxVNhopfsUnsplash1: ["michaelDziedzicLFxVNhopfsUnsplash1"],
  idkAlbumClean111: ["idkAlbumClean111"],
  itemInfo: [
    "itemInfo",
    "titlePrice",
    "usee4Urself",
    "label3",
    "popular",
    "titlePrice2",
    "idk",
    "frame1092",
    "release",
    "highestBid"
  ],

  titlePrice: ["titlePrice", "usee4Urself", "label3", "popular"],
  usee4Urself: ["usee4Urself"],
  label3: ["label3", "popular"],
  popular: ["popular"],
  titlePrice2: ["titlePrice2", "idk", "frame1092", "release", "highestBid"],
  idk: ["idk"],
  frame1092: ["frame1092", "release", "highestBid"],
  release: ["release"],
  highestBid: ["highestBid"],
  frame971: [
    "frame971",
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062"
  ],

  frame970: [
    "frame970",
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963",
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062"
  ],

  frame1104: [
    "frame1104",
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2",
    "frame963"
  ],

  productTitlePrice: [
    "productTitlePrice",
    "frame1103",
    "frame952",
    "price",
    "popular2"
  ],

  frame1103: ["frame1103"],
  frame952: ["frame952", "price", "popular2"],
  price: ["price", "popular2"],
  popular2: ["popular2"],
  frame963: ["frame963"],
  fixedBox: [
    "fixedBox",
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame958",
    "button3",
    "label4",
    "button4",
    "label5",
    "frame957",
    "serviceFee",
    "_15",
    "_2563Eth",
    "_454062"
  ],

  frame1087: [
    "frame1087",
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1"
  ],

  frame960: [
    "frame960",
    "frame959",
    "frame956",
    "frame955",
    "frame954",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1"
  ],

  frame959: ["frame959", "frame956", "frame955", "frame954"],
  frame956: ["frame956", "frame955"],
  frame955: ["frame955"],
  frame954: ["frame954"],
  avatar01: ["avatar01", "austinWadeX6Uj51N5Ce8Unsplash1"],
  austinWadeX6Uj51N5Ce8Unsplash1: ["austinWadeX6Uj51N5Ce8Unsplash1"],
  frame958: ["frame958", "button3", "label4", "button4", "label5"],
  button3: ["button3", "label4"],
  label4: ["label4"],
  button4: ["button4", "label5"],
  label5: ["label5"],
  frame957: ["frame957", "serviceFee", "_15", "_2563Eth", "_454062"],
  serviceFee: ["serviceFee"],
  _15: ["_15"],
  _2563Eth: ["_2563Eth"],
  _454062: ["_454062"],
  icons: ["icons", "share", "love"],
  share: ["share"],
  love: ["love"],
  footerDesktopLight: [
    "footerDesktopLight",
    "divider2",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider3",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider2: ["divider2"],
  footer05DesktopLight: [
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider3",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame789: [
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider3",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame787: [
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame774: ["frame774", "logo2", "letsMakeAGreatDesignTogerther"],
  logo2: ["logo2"],
  letsMakeAGreatDesignTogerther: ["letsMakeAGreatDesignTogerther"],
  frame783: [
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo"
  ],

  crypter: ["crypter"],
  frame726: ["frame726", "about", "projects", "whatWeDo"],
  about: ["about"],
  projects: ["projects"],
  whatWeDo: ["whatWeDo"],
  frame784: ["frame784", "info", "frame727"],
  info: ["info"],
  frame727: ["frame727"],
  frame786: [
    "frame786",
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame785: [
    "frame785",
    "singleInputField",
    "enterYourEmail",
    "smallCircleButton"
  ],

  singleInputField: ["singleInputField", "enterYourEmail", "smallCircleButton"],
  enterYourEmail: ["enterYourEmail"],
  smallCircleButton: ["smallCircleButton"],
  bottomBar: [
    "bottomBar",
    "divider3",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider3: ["divider3"],
  bottomBarContent: [
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  copyright2021Ui8LlcAllRightsReserved: [
    "copyright2021Ui8LlcAllRightsReserved"
  ],

  frame788: ["frame788", "weUseCookiesForBetterService", "accept"],
  weUseCookiesForBetterService: ["weUseCookiesForBetterService"],
  accept: ["accept"],
  overlay: ["overlay"],
  modalPlaceABidPlaceABid01Light: [
    "modalPlaceABidPlaceABid01Light",
    "title",
    "share2",
    "frame1064",
    "buttons2",
    "button5",
    "label6",
    "button6",
    "label7"
  ],

  title: ["title", "share2"],
  share2: ["share2"],
  frame1064: ["frame1064"],
  buttons2: ["buttons2", "button5", "label6", "button6", "label7"],
  button5: ["button5", "label6"],
  label6: ["label6"],
  button6: ["button6", "label7"],
  label7: ["label7"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPlaceABid__ArgProps,
      internalVariantPropNames: PlasmicPlaceABid__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPlaceABid__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPlaceABid";
  } else {
    func.displayName = `PlasmicPlaceABid.${nodeName}`;
  }
  return func;
}

export const PlasmicPlaceABid = Object.assign(
  // Top-level PlasmicPlaceABid renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    placeABidDesktopTabletLight: makeNodeComponent(
      "placeABidDesktopTabletLight"
    ),

    item01DesktopLight: makeNodeComponent("item01DesktopLight"),
    navDefaultDesktopLight: makeNodeComponent("navDefaultDesktopLight"),
    navContent: makeNodeComponent("navContent"),
    leftContent: makeNodeComponent("leftContent"),
    logo: makeNodeComponent("logo"),
    divider: makeNodeComponent("divider"),
    actions: makeNodeComponent("actions"),
    buttons: makeNodeComponent("buttons"),
    button: makeNodeComponent("button"),
    label: makeNodeComponent("label"),
    button2: makeNodeComponent("button2"),
    label2: makeNodeComponent("label2"),
    itemDesktopLight: makeNodeComponent("itemDesktopLight"),
    group34: makeNodeComponent("group34"),
    itemWrap: makeNodeComponent("itemWrap"),
    frame1105: makeNodeComponent("frame1105"),
    itemCard: makeNodeComponent("itemCard"),
    productImg: makeNodeComponent("productImg"),
    media10: makeNodeComponent("media10"),
    imgLibimg114: makeNodeComponent("imgLibimg114"),
    fuuJCLoSgOrJu6SUnsplash1: makeNodeComponent("fuuJCLoSgOrJu6SUnsplash1"),
    michaelDziedzicLFxVNhopfsUnsplash1: makeNodeComponent(
      "michaelDziedzicLFxVNhopfsUnsplash1"
    ),

    idkAlbumClean111: makeNodeComponent("idkAlbumClean111"),
    itemInfo: makeNodeComponent("itemInfo"),
    titlePrice: makeNodeComponent("titlePrice"),
    usee4Urself: makeNodeComponent("usee4Urself"),
    label3: makeNodeComponent("label3"),
    popular: makeNodeComponent("popular"),
    titlePrice2: makeNodeComponent("titlePrice2"),
    idk: makeNodeComponent("idk"),
    frame1092: makeNodeComponent("frame1092"),
    release: makeNodeComponent("release"),
    highestBid: makeNodeComponent("highestBid"),
    frame971: makeNodeComponent("frame971"),
    frame970: makeNodeComponent("frame970"),
    frame1104: makeNodeComponent("frame1104"),
    productTitlePrice: makeNodeComponent("productTitlePrice"),
    frame1103: makeNodeComponent("frame1103"),
    frame952: makeNodeComponent("frame952"),
    price: makeNodeComponent("price"),
    popular2: makeNodeComponent("popular2"),
    frame963: makeNodeComponent("frame963"),
    fixedBox: makeNodeComponent("fixedBox"),
    frame1087: makeNodeComponent("frame1087"),
    frame960: makeNodeComponent("frame960"),
    frame959: makeNodeComponent("frame959"),
    frame956: makeNodeComponent("frame956"),
    frame955: makeNodeComponent("frame955"),
    frame954: makeNodeComponent("frame954"),
    avatar01: makeNodeComponent("avatar01"),
    austinWadeX6Uj51N5Ce8Unsplash1: makeNodeComponent(
      "austinWadeX6Uj51N5Ce8Unsplash1"
    ),

    frame958: makeNodeComponent("frame958"),
    button3: makeNodeComponent("button3"),
    label4: makeNodeComponent("label4"),
    button4: makeNodeComponent("button4"),
    label5: makeNodeComponent("label5"),
    frame957: makeNodeComponent("frame957"),
    serviceFee: makeNodeComponent("serviceFee"),
    _15: makeNodeComponent("_15"),
    _2563Eth: makeNodeComponent("_2563Eth"),
    _454062: makeNodeComponent("_454062"),
    icons: makeNodeComponent("icons"),
    share: makeNodeComponent("share"),
    love: makeNodeComponent("love"),
    footerDesktopLight: makeNodeComponent("footerDesktopLight"),
    divider2: makeNodeComponent("divider2"),
    footer05DesktopLight: makeNodeComponent("footer05DesktopLight"),
    frame789: makeNodeComponent("frame789"),
    frame787: makeNodeComponent("frame787"),
    frame774: makeNodeComponent("frame774"),
    logo2: makeNodeComponent("logo2"),
    letsMakeAGreatDesignTogerther: makeNodeComponent(
      "letsMakeAGreatDesignTogerther"
    ),

    frame783: makeNodeComponent("frame783"),
    crypter: makeNodeComponent("crypter"),
    frame726: makeNodeComponent("frame726"),
    about: makeNodeComponent("about"),
    projects: makeNodeComponent("projects"),
    whatWeDo: makeNodeComponent("whatWeDo"),
    frame784: makeNodeComponent("frame784"),
    info: makeNodeComponent("info"),
    frame727: makeNodeComponent("frame727"),
    frame786: makeNodeComponent("frame786"),
    frame785: makeNodeComponent("frame785"),
    singleInputField: makeNodeComponent("singleInputField"),
    enterYourEmail: makeNodeComponent("enterYourEmail"),
    smallCircleButton: makeNodeComponent("smallCircleButton"),
    bottomBar: makeNodeComponent("bottomBar"),
    divider3: makeNodeComponent("divider3"),
    bottomBarContent: makeNodeComponent("bottomBarContent"),
    copyright2021Ui8LlcAllRightsReserved: makeNodeComponent(
      "copyright2021Ui8LlcAllRightsReserved"
    ),

    frame788: makeNodeComponent("frame788"),
    weUseCookiesForBetterService: makeNodeComponent(
      "weUseCookiesForBetterService"
    ),

    accept: makeNodeComponent("accept"),
    overlay: makeNodeComponent("overlay"),
    modalPlaceABidPlaceABid01Light: makeNodeComponent(
      "modalPlaceABidPlaceABid01Light"
    ),

    title: makeNodeComponent("title"),
    share2: makeNodeComponent("share2"),
    frame1064: makeNodeComponent("frame1064"),
    buttons2: makeNodeComponent("buttons2"),
    button5: makeNodeComponent("button5"),
    label6: makeNodeComponent("label6"),
    button6: makeNodeComponent("button6"),
    label7: makeNodeComponent("label7"),
    // Metadata about props expected for PlasmicPlaceABid
    internalVariantProps: PlasmicPlaceABid__VariantProps,
    internalArgProps: PlasmicPlaceABid__ArgProps
  }
);

export default PlasmicPlaceABid;
/* prettier-ignore-end */
