// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 73KhD343S1ps4YNpRNR2Mg
// Component: yMglidYWpZ
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_paper_house.module.css"; // plasmic-import: 73KhD343S1ps4YNpRNR2Mg/projectcss
import sty from "./PlasmicEditProfile.module.css"; // plasmic-import: yMglidYWpZ/css
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: pv_v81ctvL/icon
import IconsArrowLeft2Line2Icon from "./icons/PlasmicIcon__IconsArrowLeft2Line2"; // plasmic-import: 1t2qjfWHsYG/icon
import IconsArrowRightSimpleLineIcon from "./icons/PlasmicIcon__IconsArrowRightSimpleLine"; // plasmic-import: 7QCkaiMidIA/icon
import IconsPlus1LineIcon from "./icons/PlasmicIcon__IconsPlus1Line"; // plasmic-import: Ftkwe-9_WB6/icon
import IconsCloseCircleLineIcon from "./icons/PlasmicIcon__IconsCloseCircleLine"; // plasmic-import: 41hk-ShoQ8S/icon
import IconsArrowRight2Line2Icon from "./icons/PlasmicIcon__IconsArrowRight2Line2"; // plasmic-import: ojVcl76mJo1/icon

export const PlasmicEditProfile__VariantProps = new Array();

export const PlasmicEditProfile__ArgProps = new Array();

function PlasmicEditProfile__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"editProfileDesktopLight"}
            data-plasmic-override={overrides.editProfileDesktopLight}
            className={classNames(projectcss.all, sty.editProfileDesktopLight)}
          >
            <div
              data-plasmic-name={"navConnectedDesktopLight"}
              data-plasmic-override={overrides.navConnectedDesktopLight}
              className={classNames(
                projectcss.all,
                sty.navConnectedDesktopLight
              )}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"navContent"}
                data-plasmic-override={overrides.navContent}
                hasGap={true}
                className={classNames(projectcss.all, sty.navContent)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"leftContent"}
                  data-plasmic-override={overrides.leftContent}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.leftContent)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"logo"}
                    data-plasmic-override={overrides.logo}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.logo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lMcJ
                      )}
                    >
                      {"Paperhouse"}
                    </div>
                  </p.Stack>

                  <div
                    data-plasmic-name={"divider"}
                    data-plasmic-override={overrides.divider}
                    className={classNames(projectcss.all, sty.divider)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z9Ijp
                    )}
                  >
                    {"Search"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9MwuC
                    )}
                  >
                    {"How it works"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"actions"}
                  data-plasmic-override={overrides.actions}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.actions)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"buttons"}
                    data-plasmic-override={overrides.buttons}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.buttons)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button)}
                    >
                      <div
                        data-plasmic-name={"label"}
                        data-plasmic-override={overrides.label}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label
                        )}
                      >
                        {"Upload"}
                      </div>
                    </p.Stack>

                    <div
                      data-plasmic-name={"notification"}
                      data-plasmic-override={overrides.notification}
                      className={classNames(projectcss.all, sty.notification)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"statusNew"}
                        data-plasmic-override={overrides.statusNew}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.statusNew)}
                      />

                      <div
                        data-plasmic-name={"iconsBellLine"}
                        data-plasmic-override={overrides.iconsBellLine}
                        className={classNames(
                          projectcss.all,
                          sty.iconsBellLine
                        )}
                      >
                        <div
                          data-plasmic-name={"notification2Line1"}
                          data-plasmic-override={overrides.notification2Line1}
                          className={classNames(
                            projectcss.all,
                            sty.notification2Line1
                          )}
                        >
                          <GroupIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kI6Om
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.button2)}
                    >
                      <div
                        data-plasmic-name={"avatar01"}
                        data-plasmic-override={overrides.avatar01}
                        className={classNames(projectcss.all, sty.avatar01)}
                      >
                        <div
                          data-plasmic-name={"austinWadeX6Uj51N5Ce8Unsplash1"}
                          data-plasmic-override={
                            overrides.austinWadeX6Uj51N5Ce8Unsplash1
                          }
                          className={classNames(
                            projectcss.all,
                            sty.austinWadeX6Uj51N5Ce8Unsplash1
                          )}
                        />
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame925"}
                        data-plasmic-override={overrides.frame925}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame925)}
                      >
                        <div
                          data-plasmic-name={"label2"}
                          data-plasmic-override={overrides.label2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label2
                          )}
                        >
                          {"700698"}
                        </div>

                        <div
                          data-plasmic-name={"label3"}
                          data-plasmic-override={overrides.label3}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label3
                          )}
                        >
                          {"SOL"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>

              <div
                data-plasmic-name={"divider2"}
                data-plasmic-override={overrides.divider2}
                className={classNames(projectcss.all, sty.divider2)}
              />
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"editProfileDesktopLight2"}
              data-plasmic-override={overrides.editProfileDesktopLight2}
              hasGap={true}
              className={classNames(
                projectcss.all,
                sty.editProfileDesktopLight2
              )}
            >
              <div
                data-plasmic-name={"container"}
                data-plasmic-override={overrides.container}
                className={classNames(projectcss.all, sty.container)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"breadcrumbWrap"}
                  data-plasmic-override={overrides.breadcrumbWrap}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.breadcrumbWrap)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"button3"}
                    data-plasmic-override={overrides.button3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.button3)}
                  >
                    <IconsArrowLeft2Line2Icon
                      className={classNames(projectcss.all, sty.svg___0CEde)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"label4"}
                      data-plasmic-override={overrides.label4}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label4
                      )}
                    >
                      {"Back to profile"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"breadcrumb"}
                    data-plasmic-override={overrides.breadcrumb}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.breadcrumb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__swlwp
                      )}
                    >
                      {"Profile"}
                    </div>

                    <IconsArrowRightSimpleLineIcon
                      className={classNames(projectcss.all, sty.svg__cvHx3)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gZv2X
                      )}
                    >
                      {"Edit Profile"}
                    </div>
                  </p.Stack>
                </p.Stack>

                <div
                  data-plasmic-name={"divider3"}
                  data-plasmic-override={overrides.divider3}
                  className={classNames(projectcss.all, sty.divider3)}
                />
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"editProfile"}
                data-plasmic-override={overrides.editProfile}
                hasGap={true}
                className={classNames(projectcss.all, sty.editProfile)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"headline"}
                  data-plasmic-override={overrides.headline}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.headline)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vZu0O
                    )}
                  >
                    {"Edit profile"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__flf5D
                    )}
                  >
                    {
                      "You can set preferred display name, create your profile URL and manage other personal settings."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"settings"}
                  data-plasmic-override={overrides.settings}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.settings)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame946"}
                    data-plasmic-override={overrides.frame946}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame946)}
                  >
                    <div
                      data-plasmic-name={"avatar012"}
                      data-plasmic-override={overrides.avatar012}
                      className={classNames(projectcss.all, sty.avatar012)}
                    >
                      <div
                        data-plasmic-name={"austinWadeX6Uj51N5Ce8Unsplash2"}
                        data-plasmic-override={
                          overrides.austinWadeX6Uj51N5Ce8Unsplash2
                        }
                        className={classNames(
                          projectcss.all,
                          sty.austinWadeX6Uj51N5Ce8Unsplash2
                        )}
                      />
                    </div>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame944"}
                      data-plasmic-override={overrides.frame944}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame944)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame945"}
                        data-plasmic-override={overrides.frame945}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame945)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__msVr0
                          )}
                        >
                          {"Profile photo"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cWqAs
                          )}
                        >
                          {
                            "We recommend an image\nof at least 400x400.\nGifs work too 🙌"
                          }
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"button4"}
                        data-plasmic-override={overrides.button4}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.button4)}
                      >
                        <div
                          data-plasmic-name={"label5"}
                          data-plasmic-override={overrides.label5}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label5
                          )}
                        >
                          {"Upload"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"inputTextFields"}
                    data-plasmic-override={overrides.inputTextFields}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.inputTextFields)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"accountInfo"}
                      data-plasmic-override={overrides.accountInfo}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.accountInfo)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dmDZf
                        )}
                      >
                        {"Account info"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"simpleInput"}
                        data-plasmic-override={overrides.simpleInput}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.simpleInput)}
                      >
                        <div
                          data-plasmic-name={"label6"}
                          data-plasmic-override={overrides.label6}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label6
                          )}
                        >
                          {"display name"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"singleInputField"}
                          data-plasmic-override={overrides.singleInputField}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.singleInputField
                          )}
                        >
                          <div
                            data-plasmic-name={"inputCaption"}
                            data-plasmic-override={overrides.inputCaption}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.inputCaption
                            )}
                          >
                            {"Enter your display name"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"simpleInput2"}
                        data-plasmic-override={overrides.simpleInput2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.simpleInput2)}
                      >
                        <div
                          data-plasmic-name={"label7"}
                          data-plasmic-override={overrides.label7}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label7
                          )}
                        >
                          {"Custom url"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"singleInputField2"}
                          data-plasmic-override={overrides.singleInputField2}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.singleInputField2
                          )}
                        >
                          <div
                            data-plasmic-name={"inputCaption2"}
                            data-plasmic-override={overrides.inputCaption2}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.inputCaption2
                            )}
                          >
                            {"ui8.net/Your custom URL"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"simpleInput3"}
                        data-plasmic-override={overrides.simpleInput3}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.simpleInput3)}
                      >
                        <div
                          data-plasmic-name={"label8"}
                          data-plasmic-override={overrides.label8}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label8
                          )}
                        >
                          {"Bio"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"singleInputField3"}
                          data-plasmic-override={overrides.singleInputField3}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.singleInputField3
                          )}
                        >
                          <div
                            data-plasmic-name={"inputCaption3"}
                            data-plasmic-override={overrides.inputCaption3}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.inputCaption3
                            )}
                          >
                            {"About yourselt in a few words"}
                          </div>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"social"}
                      data-plasmic-override={overrides.social}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.social)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pZsfJ
                        )}
                      >
                        {"Social"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"simpleInput4"}
                        data-plasmic-override={overrides.simpleInput4}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.simpleInput4)}
                      >
                        <div
                          data-plasmic-name={"label9"}
                          data-plasmic-override={overrides.label9}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label9
                          )}
                        >
                          {"portfolio or website"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"singleInputField4"}
                          data-plasmic-override={overrides.singleInputField4}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.singleInputField4
                          )}
                        >
                          <div
                            data-plasmic-name={"inputCaption4"}
                            data-plasmic-override={overrides.inputCaption4}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.inputCaption4
                            )}
                          >
                            {"Enter URL"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"simpleInput5"}
                        data-plasmic-override={overrides.simpleInput5}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.simpleInput5)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__aFKg
                          )}
                        >
                          {"twitter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"singleInputField5"}
                          data-plasmic-override={overrides.singleInputField5}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.singleInputField5
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__maNox
                            )}
                          >
                            {"@twitter username"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"button5"}
                            data-plasmic-override={overrides.button5}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.button5)}
                          >
                            <div
                              data-plasmic-name={"label10"}
                              data-plasmic-override={overrides.label10}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.label10
                              )}
                            >
                              {"Verify account"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"button6"}
                        data-plasmic-override={overrides.button6}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.button6)}
                      >
                        <IconsPlus1LineIcon
                          className={classNames(projectcss.all, sty.svg__sDBhz)}
                          role={"img"}
                        />

                        <div
                          data-plasmic-name={"label11"}
                          data-plasmic-override={overrides.label11}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label11
                          )}
                        >
                          {"Add more social account"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uXjGb
                      )}
                    >
                      {
                        "To update your settings you should sign message through your wallet. Click 'Update profile' then sign the message"
                      }
                    </div>

                    <div
                      data-plasmic-name={"divider4"}
                      data-plasmic-override={overrides.divider4}
                      className={classNames(projectcss.all, sty.divider4)}
                    />

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"buttons2"}
                      data-plasmic-override={overrides.buttons2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.buttons2)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"button7"}
                        data-plasmic-override={overrides.button7}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.button7)}
                      >
                        <div
                          data-plasmic-name={"label12"}
                          data-plasmic-override={overrides.label12}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label12
                          )}
                        >
                          {"Update Profile"}
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame942"}
                        data-plasmic-override={overrides.frame942}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame942)}
                      >
                        <IconsCloseCircleLineIcon
                          className={classNames(projectcss.all, sty.svg__c2Wqd)}
                          role={"img"}
                        />

                        <div
                          data-plasmic-name={"label13"}
                          data-plasmic-override={overrides.label13}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.label13
                          )}
                        >
                          {"Clear all"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <div
              data-plasmic-name={"footerDesktopLight"}
              data-plasmic-override={overrides.footerDesktopLight}
              className={classNames(projectcss.all, sty.footerDesktopLight)}
            >
              <div
                data-plasmic-name={"divider5"}
                data-plasmic-override={overrides.divider5}
                className={classNames(projectcss.all, sty.divider5)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"footer05DesktopLight"}
                data-plasmic-override={overrides.footer05DesktopLight}
                hasGap={true}
                className={classNames(projectcss.all, sty.footer05DesktopLight)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame789"}
                  data-plasmic-override={overrides.frame789}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame789)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame787"}
                    data-plasmic-override={overrides.frame787}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame787)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame774"}
                      data-plasmic-override={overrides.frame774}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame774)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"logo2"}
                        data-plasmic-override={overrides.logo2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.logo2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__w1X8V
                          )}
                        >
                          {"Paperhouse"}
                        </div>
                      </p.Stack>

                      <div
                        data-plasmic-name={"letsMakeAGreatDesignTogerther"}
                        data-plasmic-override={
                          overrides.letsMakeAGreatDesignTogerther
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.letsMakeAGreatDesignTogerther
                        )}
                      >
                        {"An ecosystem for the new music industry."}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame783"}
                      data-plasmic-override={overrides.frame783}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame783)}
                    >
                      <div
                        data-plasmic-name={"crypter"}
                        data-plasmic-override={overrides.crypter}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.crypter
                        )}
                      >
                        {"From us"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame726"}
                        data-plasmic-override={overrides.frame726}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame726)}
                      >
                        <div
                          data-plasmic-name={"about"}
                          data-plasmic-override={overrides.about}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.about
                          )}
                        >
                          {"Discover"}
                        </div>

                        <div
                          data-plasmic-name={"projects"}
                          data-plasmic-override={overrides.projects}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.projects
                          )}
                        >
                          {"Connect wallet"}
                        </div>

                        <div
                          data-plasmic-name={"whatWeDo"}
                          data-plasmic-override={overrides.whatWeDo}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.whatWeDo
                          )}
                        >
                          {"Create item"}
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__igBmc
                            )}
                          >
                            {"Press"}
                          </div>
                        ) : null}
                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dhIkg
                            )}
                          >
                            {"Jobs"}
                          </div>
                        ) : null}
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame784"}
                      data-plasmic-override={overrides.frame784}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame784)}
                    >
                      <div
                        data-plasmic-name={"info"}
                        data-plasmic-override={overrides.info}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.info
                        )}
                      >
                        {"Resources"}
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame727"}
                        data-plasmic-override={overrides.frame727}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame727)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nSgPy
                          )}
                        >
                          {"Download"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0E1Wg
                          )}
                        >
                          {"Demos"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yWa6H
                          )}
                        >
                          {"Support"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    {false ? (
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame786"}
                        data-plasmic-override={overrides.frame786}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame786)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vzRc
                          )}
                        >
                          {"Join Newsletter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame785"}
                          data-plasmic-override={overrides.frame785}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame785)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xhyPh
                            )}
                          >
                            {
                              "Subscribe our newsletter to get more free design course and resource"
                            }
                          </div>

                          <div
                            data-plasmic-name={"singleInputField6"}
                            data-plasmic-override={overrides.singleInputField6}
                            className={classNames(
                              projectcss.all,
                              sty.singleInputField6
                            )}
                          >
                            <div
                              data-plasmic-name={"enterYourEmail"}
                              data-plasmic-override={overrides.enterYourEmail}
                              className={classNames(
                                projectcss.all,
                                sty.enterYourEmail
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__bdGCj
                                )}
                              >
                                {"Enter your email"}
                              </div>
                            </div>

                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"smallCircleButton"}
                              data-plasmic-override={
                                overrides.smallCircleButton
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.smallCircleButton
                              )}
                            >
                              <IconsArrowRight2Line2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___6PZUs
                                )}
                                role={"img"}
                              />
                            </p.Stack>
                          </div>
                        </p.Stack>
                      </p.Stack>
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"bottomBar"}
                    data-plasmic-override={overrides.bottomBar}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.bottomBar)}
                  >
                    <div
                      data-plasmic-name={"divider6"}
                      data-plasmic-override={overrides.divider6}
                      className={classNames(projectcss.all, sty.divider6)}
                    />

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"bottomBarContent"}
                      data-plasmic-override={overrides.bottomBarContent}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.bottomBarContent
                      )}
                    >
                      <div
                        data-plasmic-name={
                          "copyright2021Ui8LlcAllRightsReserved"
                        }
                        data-plasmic-override={
                          overrides.copyright2021Ui8LlcAllRightsReserved
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.copyright2021Ui8LlcAllRightsReserved
                        )}
                      >
                        {
                          "Copyright © 2021 Paperhouse LLC. All rights reserved."
                        }
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame788"}
                        data-plasmic-override={overrides.frame788}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame788)}
                      >
                        <div
                          data-plasmic-name={"weUseCookiesForBetterService"}
                          data-plasmic-override={
                            overrides.weUseCookiesForBetterService
                          }
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.weUseCookiesForBetterService
                          )}
                        >
                          {"We’re hiring!"}
                        </div>

                        <div
                          data-plasmic-name={"accept"}
                          data-plasmic-override={overrides.accept}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.accept
                          )}
                        >
                          {"Apply"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "editProfileDesktopLight",
    "navConnectedDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "notification",
    "statusNew",
    "iconsBellLine",
    "notification2Line1",
    "button2",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame925",
    "label2",
    "label3",
    "divider2",
    "editProfileDesktopLight2",
    "container",
    "breadcrumbWrap",
    "button3",
    "label4",
    "breadcrumb",
    "divider3",
    "editProfile",
    "headline",
    "settings",
    "frame946",
    "avatar012",
    "austinWadeX6Uj51N5Ce8Unsplash2",
    "frame944",
    "frame945",
    "button4",
    "label5",
    "inputTextFields",
    "accountInfo",
    "simpleInput",
    "label6",
    "singleInputField",
    "inputCaption",
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2",
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3",
    "social",
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4",
    "simpleInput5",
    "singleInputField5",
    "button5",
    "label10",
    "button6",
    "label11",
    "divider4",
    "buttons2",
    "button7",
    "label12",
    "frame942",
    "label13",
    "footerDesktopLight",
    "divider5",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider6",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  editProfileDesktopLight: [
    "editProfileDesktopLight",
    "navConnectedDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "notification",
    "statusNew",
    "iconsBellLine",
    "notification2Line1",
    "button2",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame925",
    "label2",
    "label3",
    "divider2",
    "editProfileDesktopLight2",
    "container",
    "breadcrumbWrap",
    "button3",
    "label4",
    "breadcrumb",
    "divider3",
    "editProfile",
    "headline",
    "settings",
    "frame946",
    "avatar012",
    "austinWadeX6Uj51N5Ce8Unsplash2",
    "frame944",
    "frame945",
    "button4",
    "label5",
    "inputTextFields",
    "accountInfo",
    "simpleInput",
    "label6",
    "singleInputField",
    "inputCaption",
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2",
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3",
    "social",
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4",
    "simpleInput5",
    "singleInputField5",
    "button5",
    "label10",
    "button6",
    "label11",
    "divider4",
    "buttons2",
    "button7",
    "label12",
    "frame942",
    "label13",
    "footerDesktopLight",
    "divider5",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider6",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  navConnectedDesktopLight: [
    "navConnectedDesktopLight",
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "notification",
    "statusNew",
    "iconsBellLine",
    "notification2Line1",
    "button2",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame925",
    "label2",
    "label3",
    "divider2"
  ],

  navContent: [
    "navContent",
    "leftContent",
    "logo",
    "divider",
    "actions",
    "buttons",
    "button",
    "label",
    "notification",
    "statusNew",
    "iconsBellLine",
    "notification2Line1",
    "button2",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame925",
    "label2",
    "label3"
  ],

  leftContent: ["leftContent", "logo", "divider"],
  logo: ["logo"],
  divider: ["divider"],
  actions: [
    "actions",
    "buttons",
    "button",
    "label",
    "notification",
    "statusNew",
    "iconsBellLine",
    "notification2Line1",
    "button2",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame925",
    "label2",
    "label3"
  ],

  buttons: [
    "buttons",
    "button",
    "label",
    "notification",
    "statusNew",
    "iconsBellLine",
    "notification2Line1",
    "button2",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame925",
    "label2",
    "label3"
  ],

  button: ["button", "label"],
  label: ["label"],
  notification: [
    "notification",
    "statusNew",
    "iconsBellLine",
    "notification2Line1"
  ],

  statusNew: ["statusNew"],
  iconsBellLine: ["iconsBellLine", "notification2Line1"],
  notification2Line1: ["notification2Line1"],
  button2: [
    "button2",
    "avatar01",
    "austinWadeX6Uj51N5Ce8Unsplash1",
    "frame925",
    "label2",
    "label3"
  ],

  avatar01: ["avatar01", "austinWadeX6Uj51N5Ce8Unsplash1"],
  austinWadeX6Uj51N5Ce8Unsplash1: ["austinWadeX6Uj51N5Ce8Unsplash1"],
  frame925: ["frame925", "label2", "label3"],
  label2: ["label2"],
  label3: ["label3"],
  divider2: ["divider2"],
  editProfileDesktopLight2: [
    "editProfileDesktopLight2",
    "container",
    "breadcrumbWrap",
    "button3",
    "label4",
    "breadcrumb",
    "divider3",
    "editProfile",
    "headline",
    "settings",
    "frame946",
    "avatar012",
    "austinWadeX6Uj51N5Ce8Unsplash2",
    "frame944",
    "frame945",
    "button4",
    "label5",
    "inputTextFields",
    "accountInfo",
    "simpleInput",
    "label6",
    "singleInputField",
    "inputCaption",
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2",
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3",
    "social",
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4",
    "simpleInput5",
    "singleInputField5",
    "button5",
    "label10",
    "button6",
    "label11",
    "divider4",
    "buttons2",
    "button7",
    "label12",
    "frame942",
    "label13"
  ],

  container: [
    "container",
    "breadcrumbWrap",
    "button3",
    "label4",
    "breadcrumb",
    "divider3"
  ],

  breadcrumbWrap: ["breadcrumbWrap", "button3", "label4", "breadcrumb"],
  button3: ["button3", "label4"],
  label4: ["label4"],
  breadcrumb: ["breadcrumb"],
  divider3: ["divider3"],
  editProfile: [
    "editProfile",
    "headline",
    "settings",
    "frame946",
    "avatar012",
    "austinWadeX6Uj51N5Ce8Unsplash2",
    "frame944",
    "frame945",
    "button4",
    "label5",
    "inputTextFields",
    "accountInfo",
    "simpleInput",
    "label6",
    "singleInputField",
    "inputCaption",
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2",
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3",
    "social",
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4",
    "simpleInput5",
    "singleInputField5",
    "button5",
    "label10",
    "button6",
    "label11",
    "divider4",
    "buttons2",
    "button7",
    "label12",
    "frame942",
    "label13"
  ],

  headline: ["headline"],
  settings: [
    "settings",
    "frame946",
    "avatar012",
    "austinWadeX6Uj51N5Ce8Unsplash2",
    "frame944",
    "frame945",
    "button4",
    "label5",
    "inputTextFields",
    "accountInfo",
    "simpleInput",
    "label6",
    "singleInputField",
    "inputCaption",
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2",
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3",
    "social",
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4",
    "simpleInput5",
    "singleInputField5",
    "button5",
    "label10",
    "button6",
    "label11",
    "divider4",
    "buttons2",
    "button7",
    "label12",
    "frame942",
    "label13"
  ],

  frame946: [
    "frame946",
    "avatar012",
    "austinWadeX6Uj51N5Ce8Unsplash2",
    "frame944",
    "frame945",
    "button4",
    "label5"
  ],

  avatar012: ["avatar012", "austinWadeX6Uj51N5Ce8Unsplash2"],
  austinWadeX6Uj51N5Ce8Unsplash2: ["austinWadeX6Uj51N5Ce8Unsplash2"],
  frame944: ["frame944", "frame945", "button4", "label5"],
  frame945: ["frame945"],
  button4: ["button4", "label5"],
  label5: ["label5"],
  inputTextFields: [
    "inputTextFields",
    "accountInfo",
    "simpleInput",
    "label6",
    "singleInputField",
    "inputCaption",
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2",
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3",
    "social",
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4",
    "simpleInput5",
    "singleInputField5",
    "button5",
    "label10",
    "button6",
    "label11",
    "divider4",
    "buttons2",
    "button7",
    "label12",
    "frame942",
    "label13"
  ],

  accountInfo: [
    "accountInfo",
    "simpleInput",
    "label6",
    "singleInputField",
    "inputCaption",
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2",
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3"
  ],

  simpleInput: ["simpleInput", "label6", "singleInputField", "inputCaption"],
  label6: ["label6"],
  singleInputField: ["singleInputField", "inputCaption"],
  inputCaption: ["inputCaption"],
  simpleInput2: [
    "simpleInput2",
    "label7",
    "singleInputField2",
    "inputCaption2"
  ],

  label7: ["label7"],
  singleInputField2: ["singleInputField2", "inputCaption2"],
  inputCaption2: ["inputCaption2"],
  simpleInput3: [
    "simpleInput3",
    "label8",
    "singleInputField3",
    "inputCaption3"
  ],

  label8: ["label8"],
  singleInputField3: ["singleInputField3", "inputCaption3"],
  inputCaption3: ["inputCaption3"],
  social: [
    "social",
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4",
    "simpleInput5",
    "singleInputField5",
    "button5",
    "label10",
    "button6",
    "label11"
  ],

  simpleInput4: [
    "simpleInput4",
    "label9",
    "singleInputField4",
    "inputCaption4"
  ],

  label9: ["label9"],
  singleInputField4: ["singleInputField4", "inputCaption4"],
  inputCaption4: ["inputCaption4"],
  simpleInput5: ["simpleInput5", "singleInputField5", "button5", "label10"],
  singleInputField5: ["singleInputField5", "button5", "label10"],
  button5: ["button5", "label10"],
  label10: ["label10"],
  button6: ["button6", "label11"],
  label11: ["label11"],
  divider4: ["divider4"],
  buttons2: ["buttons2", "button7", "label12", "frame942", "label13"],
  button7: ["button7", "label12"],
  label12: ["label12"],
  frame942: ["frame942", "label13"],
  label13: ["label13"],
  footerDesktopLight: [
    "footerDesktopLight",
    "divider5",
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider6",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider5: ["divider5"],
  footer05DesktopLight: [
    "footer05DesktopLight",
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider6",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame789: [
    "frame789",
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton",
    "bottomBar",
    "divider6",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  frame787: [
    "frame787",
    "frame774",
    "logo2",
    "letsMakeAGreatDesignTogerther",
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo",
    "frame784",
    "info",
    "frame727",
    "frame786",
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame774: ["frame774", "logo2", "letsMakeAGreatDesignTogerther"],
  logo2: ["logo2"],
  letsMakeAGreatDesignTogerther: ["letsMakeAGreatDesignTogerther"],
  frame783: [
    "frame783",
    "crypter",
    "frame726",
    "about",
    "projects",
    "whatWeDo"
  ],

  crypter: ["crypter"],
  frame726: ["frame726", "about", "projects", "whatWeDo"],
  about: ["about"],
  projects: ["projects"],
  whatWeDo: ["whatWeDo"],
  frame784: ["frame784", "info", "frame727"],
  info: ["info"],
  frame727: ["frame727"],
  frame786: [
    "frame786",
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton"
  ],

  frame785: [
    "frame785",
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton"
  ],

  singleInputField6: [
    "singleInputField6",
    "enterYourEmail",
    "smallCircleButton"
  ],

  enterYourEmail: ["enterYourEmail"],
  smallCircleButton: ["smallCircleButton"],
  bottomBar: [
    "bottomBar",
    "divider6",
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  divider6: ["divider6"],
  bottomBarContent: [
    "bottomBarContent",
    "copyright2021Ui8LlcAllRightsReserved",
    "frame788",
    "weUseCookiesForBetterService",
    "accept"
  ],

  copyright2021Ui8LlcAllRightsReserved: [
    "copyright2021Ui8LlcAllRightsReserved"
  ],

  frame788: ["frame788", "weUseCookiesForBetterService", "accept"],
  weUseCookiesForBetterService: ["weUseCookiesForBetterService"],
  accept: ["accept"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicEditProfile__ArgProps,
      internalVariantPropNames: PlasmicEditProfile__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicEditProfile__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEditProfile";
  } else {
    func.displayName = `PlasmicEditProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicEditProfile = Object.assign(
  // Top-level PlasmicEditProfile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    editProfileDesktopLight: makeNodeComponent("editProfileDesktopLight"),
    navConnectedDesktopLight: makeNodeComponent("navConnectedDesktopLight"),
    navContent: makeNodeComponent("navContent"),
    leftContent: makeNodeComponent("leftContent"),
    logo: makeNodeComponent("logo"),
    divider: makeNodeComponent("divider"),
    actions: makeNodeComponent("actions"),
    buttons: makeNodeComponent("buttons"),
    button: makeNodeComponent("button"),
    label: makeNodeComponent("label"),
    notification: makeNodeComponent("notification"),
    statusNew: makeNodeComponent("statusNew"),
    iconsBellLine: makeNodeComponent("iconsBellLine"),
    notification2Line1: makeNodeComponent("notification2Line1"),
    button2: makeNodeComponent("button2"),
    avatar01: makeNodeComponent("avatar01"),
    austinWadeX6Uj51N5Ce8Unsplash1: makeNodeComponent(
      "austinWadeX6Uj51N5Ce8Unsplash1"
    ),

    frame925: makeNodeComponent("frame925"),
    label2: makeNodeComponent("label2"),
    label3: makeNodeComponent("label3"),
    divider2: makeNodeComponent("divider2"),
    editProfileDesktopLight2: makeNodeComponent("editProfileDesktopLight2"),
    container: makeNodeComponent("container"),
    breadcrumbWrap: makeNodeComponent("breadcrumbWrap"),
    button3: makeNodeComponent("button3"),
    label4: makeNodeComponent("label4"),
    breadcrumb: makeNodeComponent("breadcrumb"),
    divider3: makeNodeComponent("divider3"),
    editProfile: makeNodeComponent("editProfile"),
    headline: makeNodeComponent("headline"),
    settings: makeNodeComponent("settings"),
    frame946: makeNodeComponent("frame946"),
    avatar012: makeNodeComponent("avatar012"),
    austinWadeX6Uj51N5Ce8Unsplash2: makeNodeComponent(
      "austinWadeX6Uj51N5Ce8Unsplash2"
    ),

    frame944: makeNodeComponent("frame944"),
    frame945: makeNodeComponent("frame945"),
    button4: makeNodeComponent("button4"),
    label5: makeNodeComponent("label5"),
    inputTextFields: makeNodeComponent("inputTextFields"),
    accountInfo: makeNodeComponent("accountInfo"),
    simpleInput: makeNodeComponent("simpleInput"),
    label6: makeNodeComponent("label6"),
    singleInputField: makeNodeComponent("singleInputField"),
    inputCaption: makeNodeComponent("inputCaption"),
    simpleInput2: makeNodeComponent("simpleInput2"),
    label7: makeNodeComponent("label7"),
    singleInputField2: makeNodeComponent("singleInputField2"),
    inputCaption2: makeNodeComponent("inputCaption2"),
    simpleInput3: makeNodeComponent("simpleInput3"),
    label8: makeNodeComponent("label8"),
    singleInputField3: makeNodeComponent("singleInputField3"),
    inputCaption3: makeNodeComponent("inputCaption3"),
    social: makeNodeComponent("social"),
    simpleInput4: makeNodeComponent("simpleInput4"),
    label9: makeNodeComponent("label9"),
    singleInputField4: makeNodeComponent("singleInputField4"),
    inputCaption4: makeNodeComponent("inputCaption4"),
    simpleInput5: makeNodeComponent("simpleInput5"),
    singleInputField5: makeNodeComponent("singleInputField5"),
    button5: makeNodeComponent("button5"),
    label10: makeNodeComponent("label10"),
    button6: makeNodeComponent("button6"),
    label11: makeNodeComponent("label11"),
    divider4: makeNodeComponent("divider4"),
    buttons2: makeNodeComponent("buttons2"),
    button7: makeNodeComponent("button7"),
    label12: makeNodeComponent("label12"),
    frame942: makeNodeComponent("frame942"),
    label13: makeNodeComponent("label13"),
    footerDesktopLight: makeNodeComponent("footerDesktopLight"),
    divider5: makeNodeComponent("divider5"),
    footer05DesktopLight: makeNodeComponent("footer05DesktopLight"),
    frame789: makeNodeComponent("frame789"),
    frame787: makeNodeComponent("frame787"),
    frame774: makeNodeComponent("frame774"),
    logo2: makeNodeComponent("logo2"),
    letsMakeAGreatDesignTogerther: makeNodeComponent(
      "letsMakeAGreatDesignTogerther"
    ),

    frame783: makeNodeComponent("frame783"),
    crypter: makeNodeComponent("crypter"),
    frame726: makeNodeComponent("frame726"),
    about: makeNodeComponent("about"),
    projects: makeNodeComponent("projects"),
    whatWeDo: makeNodeComponent("whatWeDo"),
    frame784: makeNodeComponent("frame784"),
    info: makeNodeComponent("info"),
    frame727: makeNodeComponent("frame727"),
    frame786: makeNodeComponent("frame786"),
    frame785: makeNodeComponent("frame785"),
    singleInputField6: makeNodeComponent("singleInputField6"),
    enterYourEmail: makeNodeComponent("enterYourEmail"),
    smallCircleButton: makeNodeComponent("smallCircleButton"),
    bottomBar: makeNodeComponent("bottomBar"),
    divider6: makeNodeComponent("divider6"),
    bottomBarContent: makeNodeComponent("bottomBarContent"),
    copyright2021Ui8LlcAllRightsReserved: makeNodeComponent(
      "copyright2021Ui8LlcAllRightsReserved"
    ),

    frame788: makeNodeComponent("frame788"),
    weUseCookiesForBetterService: makeNodeComponent(
      "weUseCookiesForBetterService"
    ),

    accept: makeNodeComponent("accept"),
    // Metadata about props expected for PlasmicEditProfile
    internalVariantProps: PlasmicEditProfile__VariantProps,
    internalArgProps: PlasmicEditProfile__ArgProps
  }
);

export default PlasmicEditProfile;
/* prettier-ignore-end */
